package co.xenastudios.neoskript.lang;

import co.xenastudios.neoskript.api.syntax.Expression;
import co.xenastudios.neoskript.api.registry.SyntaxRegistry;

/** Generated bulk conditions (source-grounded). One per line for compile-drop. */
public final class GenCondBulk {
    private GenCondBulk() {}

    public static void register(SyntaxRegistry registry) {
        registry.registerCondition("%object% (is|are) sedated", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.block.Block h && (h.getState() instanceof org.bukkit.block.Beehive beehive && beehive.isSedated()); }; });
        registry.registerCondition("%object% (is|are) resonating", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.block.Block h && (h.getState(false) instanceof org.bukkit.block.Bell bell && bell.isResonating()); }; });
        registry.registerCondition("%object% (is|are) ringing", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.block.Block h && (h.getState(false) instanceof org.bukkit.block.Bell bell && bell.isShaking()); }; });
        registry.registerCondition("[the] entity storage of %object% (is|are) full", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.block.Block h && (h.getState() instanceof org.bukkit.block.EntityBlockStorage<?> s && s.isFull()); }; });
        registry.registerCondition("%object% can be dispensed", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof io.papermc.paper.datacomponent.item.Equippable h && (h.dispensable()); }; });
        registry.registerCondition("%object% can be sheared off [of entities]", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof io.papermc.paper.datacomponent.item.Equippable h && (h.canBeSheared()); }; });
        registry.registerCondition("%object% can be (equipped|put) on[to] entities", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof io.papermc.paper.datacomponent.item.Equippable h && (h.equipOnInteract()); }; });
        registry.registerCondition("%object% can swap equipment [on right click|when right clicked]", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof io.papermc.paper.datacomponent.item.Equippable h && (h.swappable()); }; });
        registry.registerCondition("%object% will (lose durability|be damaged) (on [wearer['s]] injury|when [[the] wearer [is]] (hurt|injured|damaged))", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof io.papermc.paper.datacomponent.item.Equippable h && (h.damageOnHurt()); }; });
        registry.registerCondition("%object% (has|have) (chat|text) filtering (on|enabled)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.Player h && (java.lang.Boolean.TRUE.equals(h.getClientOption(com.destroystokyo.paper.ClientOption.TEXT_FILTERING_ENABLED))); }; });
        registry.registerCondition("%object% (has|have) [a] (client|custom) weather [set]", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.Player h && (h.getPlayerWeather() != null); }; });
        registry.registerCondition("%object% (has|have) glowing text", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof java.lang.Object h && ((h instanceof org.bukkit.block.Block b && b.getState() instanceof org.bukkit.block.Sign sign1 && sign1.isGlowingText()) || (h instanceof org.bukkit.inventory.ItemStack i && i.getItemMeta() instanceof org.bukkit.inventory.meta.BlockStateMeta meta && meta.getBlockState() instanceof org.bukkit.block.Sign sign2 && sign2.isGlowingText())); }; });
        registry.registerCondition("[creeper[s]] %object% (is|are) going to explode", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.LivingEntity h && (h instanceof org.bukkit.entity.Creeper && ((org.bukkit.entity.Creeper) h).isIgnited()); }; });
        registry.registerCondition("%object% (is|are) charging [a] fireball", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.LivingEntity h && (h instanceof org.bukkit.entity.Ghast && ((org.bukkit.entity.Ghast) h).isCharging()); }; });
        registry.registerCondition("%object% (is|are) conditional", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.block.Block h && (h.getBlockData() instanceof org.bukkit.block.data.type.CommandBlock && ((org.bukkit.block.data.type.CommandBlock) h.getBlockData()).isConditional()); }; });
        registry.registerCondition("%object% (is|are) dancing", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.LivingEntity h && ((h instanceof org.bukkit.entity.Allay && ((org.bukkit.entity.Allay) h).isDancing()) || (h instanceof org.bukkit.entity.Parrot && ((org.bukkit.entity.Parrot) h).isDancing()) || (h instanceof org.bukkit.entity.Piglin && ((org.bukkit.entity.Piglin) h).isDancing())); }; });
        registry.registerCondition("%object% (is|are) eating", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.LivingEntity h && ((h instanceof org.bukkit.entity.Panda && ((org.bukkit.entity.Panda) h).isEating()) || (h instanceof org.bukkit.entity.AbstractHorse && ((org.bukkit.entity.AbstractHorse) h).isEating())); }; });
        registry.registerCondition("%object% (is|are) (fire resistant|resistant to fire)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.inventory.ItemStack h && (h.getItemMeta() != null && h.getItemMeta().isFireResistant()); }; });
        registry.registerCondition("%object% ((is|are) incendiary|cause[s] a[n] (incendiary|fiery) explosion)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.Entity h && (h instanceof org.bukkit.entity.Explosive && ((org.bukkit.entity.Explosive) h).isIncendiary()); }; });
        registry.registerCondition("%object% (is|are) pathfinding", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.LivingEntity h && (h instanceof org.bukkit.entity.Mob && ((org.bukkit.entity.Mob) h).getPathfinder().hasPath()); }; });
        registry.registerCondition("%object% (is|are) playing dead", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.LivingEntity h && (h instanceof org.bukkit.entity.Axolotl && ((org.bukkit.entity.Axolotl) h).isPlayingDead()); }; });
        registry.registerCondition("%object% (is|are) responsive", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.Entity h && (h instanceof org.bukkit.entity.Interaction && ((org.bukkit.entity.Interaction) h).isResponsive()); }; });
        registry.registerCondition("%object% (is|are) screaming", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.LivingEntity h && ((h instanceof org.bukkit.entity.Goat && ((org.bukkit.entity.Goat) h).isScreaming()) || (h instanceof org.bukkit.entity.Enderman && ((org.bukkit.entity.Enderman) h).isScreaming())); }; });
        registry.registerCondition("%object% (is|are) solid", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.inventory.ItemStack h && (h.getType().isSolid()); }; });
        registry.registerCondition("%object% (is|are) stackable", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.inventory.ItemStack h && (h.getMaxStackSize() > 1); }; });
        registry.registerCondition("%object% (is|are) tameable", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.LivingEntity h && (h instanceof org.bukkit.entity.Tameable); }; });
        registry.registerCondition("%object% (is|are) transparent", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.inventory.ItemStack h && (h.getType().isTransparent()); }; });
        registry.registerCondition("%object% (is|are) unbreakable", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.inventory.ItemStack h && (h.getItemMeta() != null && h.getItemMeta().isUnbreakable()); }; });
        registry.registerCondition("%object% (is|are) valid", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.Entity h && (h.isValid()); }; });
        registry.registerCondition("%object% (has|have) enchantment glint overrid(den|e)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.inventory.ItemStack h && (h.getItemMeta() != null && h.getItemMeta().hasEnchantmentGlintOverride()); }; });
        registry.registerCondition("%object% (is|are) left( |-)handed", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.LivingEntity h && (h instanceof org.bukkit.entity.Mob ? ((org.bukkit.entity.Mob) h).isLeftHanded() : (h instanceof org.bukkit.entity.HumanEntity && ((org.bukkit.entity.HumanEntity) h).getMainHand() == org.bukkit.inventory.MainHand.LEFT)); }; });
        registry.registerCondition("[the] lid[s] of %object% (is|are) open[ed]", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.block.Block h && (h.getState() instanceof org.bukkit.block.Lidded && ((org.bukkit.block.Lidded) h.getState()).isOpen()); }; });
        registry.registerCondition("%object% (has|have) ([an] icon|icons)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.potion.PotionEffect h && (h.hasIcon()); }; });
        registry.registerCondition("%object% (has|have) particles", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.potion.PotionEffect h && (h.hasParticles()); }; });
        registry.registerCondition("%object% (is|are) ambient", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.potion.PotionEffect h && (h.isAmbient()); }; });
        registry.registerCondition("(is PvP|PvP is) enabled in %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.World h && (h.getPVP()); }; });
        registry.registerCondition("%object% (is|are) shivering", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.LivingEntity h && (h instanceof org.bukkit.entity.Strider && ((org.bukkit.entity.Strider) h).isShivering()); }; });
        registry.registerCondition("[[the] text of] %object% (has|have) [a] (drop|text) shadow", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); return o instanceof org.bukkit.entity.Display h && (h instanceof org.bukkit.entity.TextDisplay && ((org.bukkit.entity.TextDisplay) h).isShadowed()); }; });
    }
}
