package co.xenastudios.neoskript.lang;

import co.xenastudios.neoskript.api.registry.SyntaxRegistry;

/** Generated unified conditions/effects (0-4 inputs, source-grounded). */
public final class GenCEUnified {
    private GenCEUnified() {}

    public static void register(SyntaxRegistry registry) {
        registry.registerCondition("%object% (has|have) [a] loot[ ]table", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); return ((a0 instanceof org.bukkit.loot.Lootable && ((org.bukkit.loot.Lootable)a0).getLootTable() != null) || (a0 instanceof org.bukkit.block.Block && ((org.bukkit.block.Block)a0).getState() instanceof org.bukkit.loot.Lootable && ((org.bukkit.loot.Lootable)((org.bukkit.block.Block)a0).getState()).getLootTable() != null)); });
        registry.registerCondition("%object% (has|have) [persistent] data tag[s] %object%", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (a1 instanceof String && !((String)a1).isEmpty() && org.bukkit.NamespacedKey.fromString(((String)a1).toLowerCase(java.util.Locale.ENGLISH)) != null && ((a0 instanceof org.bukkit.persistence.PersistentDataHolder && ((org.bukkit.persistence.PersistentDataHolder)a0).getPersistentDataContainer().has(org.bukkit.NamespacedKey.fromString(((String)a1).toLowerCase(java.util.Locale.ENGLISH)))) || (a0 instanceof org.bukkit.inventory.ItemStack && ((org.bukkit.inventory.ItemStack)a0).getItemMeta() != null && ((org.bukkit.inventory.ItemStack)a0).getItemMeta().getPersistentDataContainer().has(org.bukkit.NamespacedKey.fromString(((String)a1).toLowerCase(java.util.Locale.ENGLISH)))) || (a0 instanceof org.bukkit.block.Block && ((org.bukkit.block.Block)a0).getState() instanceof org.bukkit.persistence.PersistentDataHolder && ((org.bukkit.persistence.PersistentDataHolder)((org.bukkit.block.Block)a0).getState()).getPersistentDataContainer().has(org.bukkit.NamespacedKey.fromString(((String)a1).toLowerCase(java.util.Locale.ENGLISH)))))); });
        registry.registerCondition("%object% (is|are) evenly divisible by %object% [with [a] tolerance [of] %object%]", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return (a0 instanceof java.lang.Number && a1 instanceof java.lang.Number && ((java.lang.Number)a1).doubleValue() != 0 && (a2 instanceof java.lang.Number ? ((java.lang.Number)a2).doubleValue() : 1e-10) > 0 && !java.lang.Double.isNaN(a2 instanceof java.lang.Number ? ((java.lang.Number)a2).doubleValue() : 1e-10) && ((java.lang.Number)a1).doubleValue() >= (a2 instanceof java.lang.Number ? ((java.lang.Number)a2).doubleValue() : 1e-10) && (java.lang.Math.abs(((java.lang.Number)a0).doubleValue() % ((java.lang.Number)a1).doubleValue()) <= (a2 instanceof java.lang.Number ? ((java.lang.Number)a2).doubleValue() : 1e-10) || java.lang.Math.abs(((java.lang.Number)a0).doubleValue() % ((java.lang.Number)a1).doubleValue()) >= ((java.lang.Number)a1).doubleValue() - (a2 instanceof java.lang.Number ? ((java.lang.Number)a2).doubleValue() : 1e-10))); });
        registry.registerCondition("%object%'[s] hand[s] (is|are) raised", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.entity.LivingEntity && ((org.bukkit.entity.LivingEntity)a0).isHandRaised()); });
        registry.registerCondition("%object%'[s] main hand[s] (is|are) raised", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.entity.LivingEntity && ((org.bukkit.entity.LivingEntity)a0).isHandRaised() && ((org.bukkit.entity.LivingEntity)a0).getHandRaised() == org.bukkit.inventory.EquipmentSlot.HAND); });
        registry.registerCondition("%object%'[s] off[ |-]hand[s] (is|are) raised", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.entity.LivingEntity && ((org.bukkit.entity.LivingEntity)a0).isHandRaised() && ((org.bukkit.entity.LivingEntity)a0).getHandRaised() == org.bukkit.inventory.EquipmentSlot.OFF_HAND); });
        registry.registerCondition("hand[s] of %object% (is|are) raised", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.entity.LivingEntity && ((org.bukkit.entity.LivingEntity)a0).isHandRaised()); });
        registry.registerCondition("main hand[s] of %object% (is|are) raised", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.entity.LivingEntity && ((org.bukkit.entity.LivingEntity)a0).isHandRaised() && ((org.bukkit.entity.LivingEntity)a0).getHandRaised() == org.bukkit.inventory.EquipmentSlot.HAND); });
        registry.registerCondition("off[ |-]hand[s] of %object% (is|are) raised", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.entity.LivingEntity && ((org.bukkit.entity.LivingEntity)a0).isHandRaised() && ((org.bukkit.entity.LivingEntity)a0).getHandRaised() == org.bukkit.inventory.EquipmentSlot.OFF_HAND); });
        registry.registerCondition("chunk [at] %number%, %number% (in|of) [world] %world% is loaded", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return (a0 instanceof java.lang.Number && a1 instanceof java.lang.Number && a2 instanceof org.bukkit.World && ((org.bukkit.World) a2).isChunkLoaded(((java.lang.Number) a0).intValue(), ((java.lang.Number) a1).intValue())); });
        registry.registerCondition("world[s] %worlds% (is|are) loaded", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.World && org.bukkit.Bukkit.getWorld(((org.bukkit.World) a0).getName()) != null); });
        registry.registerCondition("%blocks/entities% (is|are) lootable", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.loot.Lootable || (a0 instanceof org.bukkit.block.Block && ((org.bukkit.block.Block) a0).getState() instanceof org.bukkit.loot.Lootable)); });
        registry.registerCondition("%itemstacks/entities% (is|are) of type[s] %itemtypes/entitydatas%", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof org.bukkit.inventory.ItemStack && a1 instanceof org.bukkit.inventory.ItemStack && ((org.bukkit.inventory.ItemStack) a0).getType() == ((org.bukkit.inventory.ItemStack) a1).getType()) || (a0 instanceof org.bukkit.entity.Entity && a1 instanceof org.bukkit.entity.EntityType && ((org.bukkit.entity.Entity) a0).getType() == (org.bukkit.entity.EntityType) a1)); });
        registry.registerCondition("%itemtypes% (is|are) %blocks/blockdatas%'s preferred tool[s]", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (a0 instanceof org.bukkit.inventory.ItemStack && ((a1 instanceof org.bukkit.block.Block && ((org.bukkit.block.Block) a1).isPreferredTool((org.bukkit.inventory.ItemStack) a0)) || (a1 instanceof org.bukkit.block.data.BlockData && ((org.bukkit.block.data.BlockData) a1).isPreferredTool((org.bukkit.inventory.ItemStack) a0)))); });
        registry.registerCondition("%itemtypes% (is|are) [the|a] preferred tool[s] (for|of) %blocks/blockdatas%", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (a0 instanceof org.bukkit.inventory.ItemStack && ((a1 instanceof org.bukkit.block.Block && ((org.bukkit.block.Block) a1).isPreferredTool((org.bukkit.inventory.ItemStack) a0)) || (a1 instanceof org.bukkit.block.data.BlockData && ((org.bukkit.block.data.BlockData) a1).isPreferredTool((org.bukkit.inventory.ItemStack) a0)))); });
        registry.registerCondition("%itemtypes/entities/entitydatas% (is|are) tagged (as|with) %minecrafttags%", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (a1 instanceof org.bukkit.Tag && ((a0 instanceof org.bukkit.inventory.ItemStack && ((org.bukkit.Tag) a1).isTagged(((org.bukkit.inventory.ItemStack) a0).getType())) || (a0 instanceof org.bukkit.entity.Entity && ((org.bukkit.Tag) a1).isTagged(((org.bukkit.entity.Entity) a0).getType())) || (a0 instanceof org.bukkit.entity.EntityType && ((org.bukkit.Tag) a1).isTagged((org.bukkit.entity.EntityType) a0)))); });
        registry.registerCondition("%object% (is|are) within %object% and %object%", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return (a0 instanceof org.bukkit.Location loc && a1 instanceof org.bukkit.Location c1 && a2 instanceof org.bukkit.Location c2 && c1.getWorld() != null && c1.getWorld().equals(c2.getWorld()) && c1.getWorld().equals(loc.getWorld()) && org.bukkit.util.BoundingBox.of(c1, c2).contains(loc.toVector())); });
        registry.registerCondition("%object% (is|are) (within|in[side [of]]) %object%", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (a0 instanceof org.bukkit.Location loc && (a1 instanceof org.bukkit.entity.Entity ent ? ent.getBoundingBox().contains(loc.toVector()) : a1 instanceof org.bukkit.block.Block blk ? blk.getCollisionShape().getBoundingBoxes().stream().anyMatch(bb -> bb.contains(loc.toVector().subtract(blk.getLocation().toVector()))) : a1 instanceof org.bukkit.Chunk ch ? (loc.getWorld() != null && loc.getChunk().equals(ch)) : a1 instanceof org.bukkit.World w ? w.equals(loc.getWorld()) : a1 instanceof org.bukkit.WorldBorder wb ? wb.isInside(loc) : false)); });
        registry.registerCondition("%object% (is|are) within %object% (block|metre|meter)[s] (around|of) %object%", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return (a0 instanceof org.bukkit.Location loc && a2 instanceof org.bukkit.Location center && a1 instanceof Number num && loc.getWorld() != null && loc.getWorld().equals(center.getWorld()) && loc.distanceSquared(center) <= num.doubleValue() * num.doubleValue() * 1.00001); });
        registry.registerEffect("generate [the] loot (of|using) %object% [(with|using) %object%] in %object%", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); if (a0 instanceof org.bukkit.loot.LootTable && a2 instanceof org.bukkit.inventory.Inventory) { org.bukkit.loot.LootContext __ctx; if (a1 instanceof org.bukkit.loot.LootContext) { __ctx = (org.bukkit.loot.LootContext) a1; } else { __ctx = new org.bukkit.loot.LootContext.Builder(org.bukkit.Bukkit.getWorlds().get(0).getSpawnLocation()).build(); } try { ((org.bukkit.loot.LootTable) a0).fillInventory((org.bukkit.inventory.Inventory) a2, java.util.concurrent.ThreadLocalRandom.current(), __ctx); } catch (java.lang.IllegalArgumentException __ignore) {} }; });
        registry.registerEffect("enable PvP [in %object%]", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); if (a0 instanceof org.bukkit.World w) w.setGameRule(org.bukkit.GameRule.PVP, true);; });
        registry.registerEffect("disable PVP [in %object%]", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); if (a0 instanceof org.bukkit.World w) w.setGameRule(org.bukkit.GameRule.PVP, false);; });
        registry.registerEffect("rotate %object% by x %object%, y %object%(, [and]| and) z %object%", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); Object a3 = a.get(3).getSingle(ctx); if (a1 instanceof java.lang.Number nx && a2 instanceof java.lang.Number ny && a3 instanceof java.lang.Number nz) { float radX = (float) (nx.floatValue() * java.lang.Math.PI / 180); float radY = (float) (ny.floatValue() * java.lang.Math.PI / 180); float radZ = (float) (nz.floatValue() * java.lang.Math.PI / 180); if (a0 instanceof org.joml.Quaternionf q) { q.rotateZYX(radZ, radY, radX); } else if (a0 instanceof org.bukkit.entity.Display d) { org.bukkit.util.Transformation t = d.getTransformation(); d.setTransformation(new org.bukkit.util.Transformation(t.getTranslation(), t.getLeftRotation().rotateZYX(radZ, radY, radX), t.getScale(), t.getRightRotation())); } }; });
        registry.registerEffect("make %object% see %object% as %object%", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); if (a0 instanceof org.bukkit.entity.Player p && a1 instanceof org.bukkit.Location loc && a2 instanceof org.bukkit.block.data.BlockData bd) p.sendBlockChange(loc, bd);; });
        registry.registerEffect("make %object% see %object% as [the|its] (original|normal|actual) [block]", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); if (a0 instanceof org.bukkit.entity.Player p && a1 instanceof org.bukkit.Location loc) p.sendBlockChange(loc, loc.getBlock().getBlockData());; });
        registry.registerEffect("(stop|shut[ ]down) [the] server", a -> ctx -> {  org.bukkit.Bukkit.shutdown();; });
        registry.registerEffect("restart [the] server", a -> ctx -> {  org.bukkit.Bukkit.spigot().restart();; });
        registry.registerEffect("(make|let|force) %object% [to] (ride|mount) [(in|on)] %object%", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); if (a0 instanceof org.bukkit.entity.Entity && a1 instanceof org.bukkit.entity.Entity) { ((org.bukkit.entity.Entity) a0).leaveVehicle(); ((org.bukkit.entity.Entity) a1).addPassenger((org.bukkit.entity.Entity) a0); }; });
        registry.registerEffect("(make|let|force) %object% [to] (dismount|(dismount|leave) (from|of|) (any|the[ir]|his|her|) vehicle[s])", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); if (a0 instanceof org.bukkit.entity.Entity) ((org.bukkit.entity.Entity) a0).leaveVehicle();; });
        registry.registerEffect("(eject|dismount) (any|the|) passenger[s] (of|from) %object%", a -> ctx -> { Object a0 = a.get(0).getSingle(ctx); if (a0 instanceof org.bukkit.entity.Entity) ((org.bukkit.entity.Entity) a0).eject();; });
    }
}
