package co.xenastudios.neoskript.lang;

import co.xenastudios.neoskript.api.syntax.Expression;
import co.xenastudios.neoskript.api.registry.SyntaxRegistry;

/** Generated bulk effects (source-grounded). One per line for compile-drop. */
public final class GenEffBulk {
    private GenEffBulk() {}

    public static void register(SyntaxRegistry registry) {
        registry.registerEffect("apply bone[ ]meal[s] to %object% %object% times", a -> { Expression<?> src = a.get(0); Expression<?> ve = a.get(1); return ctx -> { Object o = src.getSingle(ctx); Object v = ve.getSingle(ctx); if (o instanceof org.bukkit.block.Block h) { int times = 1; if (v instanceof Number) times = ((Number) v).intValue(); if (times < 0) times = 0; for (int i = 0; i < times; i++) h.applyBoneMeal(org.bukkit.block.BlockFace.UP); } }; });
        registry.registerEffect("(affect|afflict) %object% with %object%", a -> { Expression<?> src = a.get(0); Expression<?> ve = a.get(1); return ctx -> { Object o = src.getSingle(ctx); Object v = ve.getSingle(ctx); if (o instanceof org.bukkit.entity.LivingEntity h) { if (v instanceof org.bukkit.potion.PotionEffect) h.addPotionEffect((org.bukkit.potion.PotionEffect) v); } }; });
        registry.registerEffect("(clear|empty) the (stored entities|entity storage) of %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.block.Block h) { org.bukkit.block.BlockState _s = h.getState(); if (_s instanceof org.bukkit.block.EntityBlockStorage) { org.bukkit.block.EntityBlockStorage<?> _st = (org.bukkit.block.EntityBlockStorage<?>) _s; _st.clearEntities(); _st.update(true, false); }; } }; });
        registry.registerEffect("(dye|colo[u]r|paint) %object% %object%", a -> { Expression<?> src = a.get(0); Expression<?> ve = a.get(1); return ctx -> { Object o = src.getSingle(ctx); Object v = ve.getSingle(ctx); if (o instanceof org.bukkit.inventory.ItemStack h) { org.bukkit.Color _c = null; if (v instanceof org.bukkit.Color) _c = (org.bukkit.Color) v; else if (v instanceof org.bukkit.DyeColor) _c = ((org.bukkit.DyeColor) v).getColor(); if (_c != null) { org.bukkit.inventory.meta.ItemMeta _m = h.getItemMeta(); if (_m instanceof org.bukkit.inventory.meta.LeatherArmorMeta) { ((org.bukkit.inventory.meta.LeatherArmorMeta) _m).setColor(_c); h.setItemMeta(_m); } else if (_m instanceof org.bukkit.inventory.meta.MapMeta) { ((org.bukkit.inventory.meta.MapMeta) _m).setColor(_c); h.setItemMeta(_m); } else if (_m instanceof org.bukkit.inventory.meta.PotionMeta) { ((org.bukkit.inventory.meta.PotionMeta) _m).setColor(_c); h.setItemMeta(_m); } }; } }; });
        registry.registerEffect("make command block[s] %object% conditional", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.block.Block h) { org.bukkit.block.data.BlockData _d = h.getBlockData(); if (_d instanceof org.bukkit.block.data.type.CommandBlock) { org.bukkit.block.data.type.CommandBlock _c = (org.bukkit.block.data.type.CommandBlock) _d; _c.setConditional(true); h.setBlockData(_c); }; } }; });
        registry.registerEffect("make %object% (start dancing|dance)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.LivingEntity h) { if (h instanceof org.bukkit.entity.Allay) { ((org.bukkit.entity.Allay) h).startDancing(); } else if (h instanceof org.bukkit.entity.Piglin) { ((org.bukkit.entity.Piglin) h).setDancing(true); }; } }; });
        registry.registerEffect("disenchant %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.inventory.ItemStack h) { for (org.bukkit.enchantments.Enchantment e : new java.util.HashSet<>(h.getEnchantments().keySet())) h.removeEnchantment(e); org.bukkit.inventory.meta.ItemMeta m = h.getItemMeta(); if (m instanceof org.bukkit.inventory.meta.EnchantmentStorageMeta es) { for (org.bukkit.enchantments.Enchantment e2 : new java.util.HashSet<>(es.getStoredEnchants().keySet())) es.removeStoredEnchant(e2); h.setItemMeta(m); }; } }; });
        registry.registerEffect("make %object% (randomly teleport|teleport randomly)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.Enderman h) { h.teleport(); } }; });
        registry.registerEffect("(make|let) %object% (lose durability|be damaged) (on [wearer['s]] injury|when [[the] wearer [is]] (hurt|injured|damaged))", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.inventory.meta.components.EquippableComponent h) { h.setDamageOnHurt(true); } }; });
        registry.registerEffect("allow %object% to be sheared off [of entities]", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.inventory.meta.components.EquippableComponent h) { h.setCanBeSheared(true); } }; });
        registry.registerEffect("(allow|force) %object% to swap equipment [on right click|when right clicked]", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.inventory.meta.components.EquippableComponent h) { h.setSwappable(true); } }; });
        registry.registerEffect("(expand|grow) [the] diameter of %object% by %object%", a -> { Expression<?> src = a.get(0); Expression<?> ve = a.get(1); return ctx -> { Object o = src.getSingle(ctx); Object v = ve.getSingle(ctx); if (o instanceof org.bukkit.WorldBorder h) { if (v instanceof Number n) h.setSize(h.getSize() + n.doubleValue()); } }; });
        registry.registerEffect("create an explosion at %object% with force %object%", a -> { Expression<?> src = a.get(0); Expression<?> ve = a.get(1); return ctx -> { Object o = src.getSingle(ctx); Object v = ve.getSingle(ctx); if (o instanceof org.bukkit.Location h) { if (v instanceof Number n && h.getWorld() != null) h.getWorld().createExplosion(h, n.floatValue(), false); } }; });
        registry.registerEffect("make %object% start eating", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.LivingEntity h) { if (h instanceof org.bukkit.entity.Panda p) { p.setEating(true); } else if (h instanceof org.bukkit.entity.AbstractHorse ah) { ah.setEating(true); }; } }; });
        registry.registerEffect("(force|make) %object% [to] [start] glint[ing]", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.inventory.ItemStack h) { org.bukkit.inventory.meta.ItemMeta m = h.getItemMeta(); if (m != null) { m.setEnchantmentGlintOverride(true); h.setItemMeta(m); }; } }; });
        registry.registerEffect("make %object% get on (its|their) back[s]", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.LivingEntity h) { if (h instanceof org.bukkit.entity.Panda p) { p.setOnBack(true); }; } }; });
        registry.registerEffect("remove both horns of %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.LivingEntity h) { if (h instanceof org.bukkit.entity.Goat) { org.bukkit.entity.Goat g = (org.bukkit.entity.Goat) h; g.setLeftHorn(true); g.setRightHorn(true); }; } }; });
        registry.registerEffect("(add|insert) %object% [in[ ]]to [the] (stored entities|entity storage) of %object%", a -> { Expression<?> src = a.get(0); Expression<?> ve = a.get(1); return ctx -> { Object o = src.getSingle(ctx); Object v = ve.getSingle(ctx); if (o instanceof org.bukkit.entity.LivingEntity h) { if (v instanceof org.bukkit.block.Block) { org.bukkit.block.BlockState state = ((org.bukkit.block.Block) v).getState(); if (state instanceof org.bukkit.block.Beehive && h instanceof org.bukkit.entity.Bee) { org.bukkit.block.Beehive hive = (org.bukkit.block.Beehive) state; if (hive.getEntityCount() < hive.getMaxEntities()) { hive.addEntity((org.bukkit.entity.Bee) h); hive.update(true, false); } } }; } }; });
        registry.registerEffect("hide [the] entire tool[ ]tip of %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.inventory.ItemStack h) { org.bukkit.inventory.meta.ItemMeta meta = h.getItemMeta(); if (meta != null) { meta.setHideTooltip(true); h.setItemMeta(meta); }; } }; });
        registry.registerEffect("load [the] world[s] %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof java.lang.String h) { new org.bukkit.WorldCreator(h).createWorld(); } }; });
        registry.registerEffect("make %object% sense [a] disturbance %object%", a -> { Expression<?> src = a.get(0); Expression<?> ve = a.get(1); return ctx -> { Object o = src.getSingle(ctx); Object v = ve.getSingle(ctx); if (o instanceof org.bukkit.entity.LivingEntity h) { if (h instanceof org.bukkit.entity.Warden w && v instanceof org.bukkit.Location loc) w.setDisturbanceLocation(loc); } }; });
        registry.registerEffect("make %object% (start screaming|scream)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.LivingEntity h) { if (h instanceof org.bukkit.entity.Goat g) { g.setScreaming(true); } else if (h instanceof org.bukkit.entity.Enderman e) { e.setScreaming(true); }; } }; });
        registry.registerEffect("make %object% (fire resistant|resistant to fire)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.inventory.ItemStack h) { org.bukkit.inventory.meta.ItemMeta meta = h.getItemMeta(); if (meta != null) { meta.setFireResistant(true); h.setItemMeta(meta); }; } }; });
        registry.registerEffect("make %object% ram %object%", a -> { Expression<?> src = a.get(0); Expression<?> ve = a.get(1); return ctx -> { Object o = src.getSingle(ctx); Object v = ve.getSingle(ctx); if (o instanceof org.bukkit.entity.LivingEntity h) { if (h instanceof org.bukkit.entity.Goat g && v instanceof org.bukkit.entity.LivingEntity lv) g.ram(lv); } }; });
        registry.registerEffect("make %object% responsive", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.Entity h) { if (h instanceof org.bukkit.entity.Interaction i) i.setResponsive(true); } }; });
        registry.registerEffect("make %object% (start rolling|roll)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.Panda h) { h.setRolling(true); } }; });
        registry.registerEffect("make %object% (start sneezing|sneeze)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.Panda h) { h.setSneezing(true); } }; });
        registry.registerEffect("make %object% (say|send [the] message[s]) %object%", a -> { Expression<?> src = a.get(0); Expression<?> ve = a.get(1); return ctx -> { Object o = src.getSingle(ctx); Object v = ve.getSingle(ctx); if (o instanceof org.bukkit.entity.Player h) { if (v != null) h.chat(String.valueOf(v)); } }; });
        registry.registerEffect("make %object% have glowing text", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.block.Block h) { org.bukkit.block.BlockState state = h.getState(); if (state instanceof org.bukkit.block.Sign sign) { sign.setGlowingText(true); state.update(); }; } }; });
        registry.registerEffect("(open|show) book %object% (to|for) %object%", a -> { Expression<?> src = a.get(0); Expression<?> ve = a.get(1); return ctx -> { Object o = src.getSingle(ctx); Object v = ve.getSingle(ctx); if (o instanceof org.bukkit.inventory.ItemStack h) { if (h != null && h.getType() == org.bukkit.Material.WRITTEN_BOOK && v instanceof org.bukkit.entity.Player p) p.openBook(h); } }; });
        registry.registerEffect("open [the] lid[s] (of|for) %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.block.Block h) { org.bukkit.block.BlockState state = h.getState(); if (state instanceof org.bukkit.block.Lidded lidded) lidded.open(); } }; });
        registry.registerEffect("make %object% (pathfind|move) to[wards] %object%", a -> { Expression<?> src = a.get(0); Expression<?> ve = a.get(1); return ctx -> { Object o = src.getSingle(ctx); Object v = ve.getSingle(ctx); if (o instanceof org.bukkit.entity.Mob h) { if (v instanceof org.bukkit.entity.LivingEntity le) h.getPathfinder().moveTo(le, 1.0); else if (v instanceof org.bukkit.Location loc) h.getPathfinder().moveTo(loc, 1.0); } }; });
        registry.registerEffect("make %object% (start playing|play) dead", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.Axolotl h) { h.setPlayingDead(true); } }; });
        registry.registerEffect("(cure|unpoison) %object% [(from|of) poison]", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.LivingEntity h) { h.removePotionEffect(org.bukkit.potion.PotionEffectType.POISON); } }; });

        registry.registerEffect("(release|evict) [the] (stored entities|entity storage) of %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.block.Block h) { org.bukkit.block.BlockState state = h.getState(); if (state instanceof org.bukkit.block.EntityBlockStorage<?> storage) storage.releaseEntities(); } }; });
        registry.registerEffect("ring %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.block.Block h) { org.bukkit.block.BlockState state = h.getState(); if (state instanceof org.bukkit.block.Bell bell) bell.ring((org.bukkit.entity.Entity) null, (org.bukkit.block.BlockFace) null); } }; });
        registry.registerEffect("send [the] resource pack to %object% from [the] URL %object%", a -> { Expression<?> src = a.get(0); Expression<?> ve = a.get(1); return ctx -> { Object o = src.getSingle(ctx); Object v = ve.getSingle(ctx); if (o instanceof org.bukkit.entity.Player h) { if (v instanceof String url) { try { h.setResourcePack(url); } catch (Exception ignored) {} }; } }; });
        registry.registerEffect("shear %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.LivingEntity h) { if (h instanceof io.papermc.paper.entity.Shearable s) { if (s.readyToBeSheared()) s.shear(); } else if (h instanceof org.bukkit.entity.Sheep sheep) sheep.setSheared(true); else if (h instanceof org.bukkit.entity.Snowman snowman) snowman.setDerp(true); } }; });
        registry.registerEffect("make %object% (start sprinting|sprint)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.Player h) { h.setSprinting(true); } }; });
        registry.registerEffect("make %object% start shivering", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.LivingEntity h) { if (h instanceof org.bukkit.entity.Strider strider) strider.setShivering(true); } }; });
        registry.registerEffect("(apply|add) (drop|text) shadow to [[the] text of] %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.Display h) { if (h instanceof org.bukkit.entity.TextDisplay td) td.setShadowed(true); } }; });
        registry.registerEffect("make %object% visible through (blocks|walls)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.Display h) { if (h instanceof org.bukkit.entity.TextDisplay td) td.setSeeThrough(true); } }; });
        registry.registerEffect("(toggle|switch) [[the] state of] %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.block.Block h) { org.bukkit.block.data.BlockData data = h.getBlockData(); if (data instanceof org.bukkit.block.data.Openable openable) { openable.setOpen(!openable.isOpen()); h.setBlockData(data); } else if (data instanceof org.bukkit.block.data.Powerable powerable) { powerable.setPowered(!powerable.isPowered()); h.setBlockData(data); }; } }; });
        registry.registerEffect("show [the] (custom|display)[ ]name of %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.Entity h) { h.setCustomNameVisible(true); } }; });
        registry.registerEffect("allow %object% to pick([ ]up items| items up)", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.LivingEntity h) { h.setCanPickupItems(true); } }; });
        registry.registerEffect("update %object% (as|to be) %object%", a -> { Expression<?> src = a.get(0); Expression<?> ve = a.get(1); return ctx -> { Object o = src.getSingle(ctx); Object v = ve.getSingle(ctx); if (o instanceof org.bukkit.block.Block h) { if (v instanceof org.bukkit.block.data.BlockData bd) h.setBlockData(bd, true); } }; });

        registry.registerEffect("zombify %object%", a -> { Expression<?> src = a.get(0); return ctx -> { Object o = src.getSingle(ctx); if (o instanceof org.bukkit.entity.Villager h) { h.zombify(); } }; });
    }
}
