package co.xenastudios.neoskript.lang;

import co.xenastudios.neoskript.api.syntax.Expression;
import co.xenastudios.neoskript.api.registry.SyntaxRegistry;
import co.xenastudios.neoskript.core.expression.ComputedExpression;
import co.xenastudios.neoskript.core.expression.ComputedListExpression;

/** Generated multi-argument value expressions (source-grounded). One per line for compile-drop. */
public final class GenExprMulti {
    private GenExprMulti() {}

    public static void register(SyntaxRegistry registry) {
        registry.registerExpression("[a|the] (round[ed] down|floored) %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (!(a0 instanceof java.lang.Number n) ? null : java.lang.Long.valueOf((long) java.lang.Math.floor(n.doubleValue()))); }));
        registry.registerExpression("%object% (round[ed] down|floored)", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (!(a0 instanceof java.lang.Number n) ? null : java.lang.Long.valueOf((long) java.lang.Math.floor(n.doubleValue()))); }));
        registry.registerExpression("[a|the] round[ed] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (!(a0 instanceof java.lang.Number n) ? null : java.lang.Long.valueOf(java.lang.Math.round(n.doubleValue()))); }));
        registry.registerExpression("%object% round[ed]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (!(a0 instanceof java.lang.Number n) ? null : java.lang.Long.valueOf(java.lang.Math.round(n.doubleValue()))); }));
        registry.registerExpression("[a|the] (round[ed] up|ceil[ing]ed) %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (!(a0 instanceof java.lang.Number n) ? null : java.lang.Long.valueOf((long) java.lang.Math.ceil(n.doubleValue()))); }));
        registry.registerExpression("%object% (round[ed] up|ceil[ing]ed)", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (!(a0 instanceof java.lang.Number n) ? null : java.lang.Long.valueOf((long) java.lang.Math.ceil(n.doubleValue()))); }));
        registry.registerExpression("%object% dot %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.util.Vector v0) || !(a1 instanceof org.bukkit.util.Vector v1) ? null : v0.dot(v1)); }));
        registry.registerExpression("[the] anger level [of] %object% towards %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.entity.Warden w) || !(a1 instanceof org.bukkit.entity.Entity e) ? null : w.getAnger(e)); }));
        registry.registerExpression("%object%'[s] anger level towards %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.entity.Warden w) || !(a1 instanceof org.bukkit.entity.Entity e) ? null : w.getAnger(e)); }));
        registry.registerExpression("[(all [[of] the]|the)] characters (between|from) %object% (and|to) %object%", Object.class, a -> new ComputedListExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object _c = (!(a0 instanceof String s0) || !(a1 instanceof String s1) || s0.isEmpty() || s1.isEmpty() ? null : java.util.stream.IntStream.rangeClosed(0, Math.abs(s0.charAt(0) - s1.charAt(0))).mapToObj(k -> String.valueOf((char)(s0.charAt(0) <= s1.charAt(0) ? s0.charAt(0) + k : s0.charAt(0) - k))).collect(java.util.stream.Collectors.toList())); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[(all [[of] the]|the)] alphanumeric characters (between|from) %object% (and|to) %object%", Object.class, a -> new ComputedListExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object _c = (!(a0 instanceof String s0) || !(a1 instanceof String s1) || s0.isEmpty() || s1.isEmpty() ? null : java.util.stream.IntStream.rangeClosed(0, Math.abs(s0.charAt(0) - s1.charAt(0))).mapToObj(k -> String.valueOf((char)(s0.charAt(0) <= s1.charAt(0) ? s0.charAt(0) + k : s0.charAt(0) - k))).filter(c -> Character.isLetterOrDigit(c.charAt(0))).collect(java.util.stream.Collectors.toList())); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] %object% attribute [value] of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.attribute.Attribute attr) || !(a1 instanceof org.bukkit.attribute.Attributable att) || att.getAttribute(attr) == null ? null : att.getAttribute(attr).getBaseValue()); }));
        registry.registerExpression("[the] %object% (total|final|modified) attribute [value] of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.attribute.Attribute attr) || !(a1 instanceof org.bukkit.attribute.Attributable att) || att.getAttribute(attr) == null ? null : att.getAttribute(attr).getValue()); }));
        registry.registerExpression("%object%'[s] %object% attribute [value]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a1 instanceof org.bukkit.attribute.Attribute attr) || !(a0 instanceof org.bukkit.attribute.Attributable att) || att.getAttribute(attr) == null ? null : att.getAttribute(attr).getBaseValue()); }));
        registry.registerExpression("%object%'[s] %object% (total|final|modified) attribute [value]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a1 instanceof org.bukkit.attribute.Attribute attr) || !(a0 instanceof org.bukkit.attribute.Attributable att) || att.getAttribute(attr) == null ? null : att.getAttribute(attr).getValue()); }));
        registry.registerExpression("[vector] projection [of] %object% on[to] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.util.Vector v0) || !(a1 instanceof org.bukkit.util.Vector v1) ? null : v1.clone().multiply(v0.dot(v1) / v1.lengthSquared())); }));
        registry.registerExpression("a random character from %object% to %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof java.lang.String s0) || !(a1 instanceof java.lang.String s1) || s0.isEmpty() || s1.isEmpty() ? null : String.valueOf((char)(java.util.concurrent.ThreadLocalRandom.current().nextInt(Math.abs(s0.charAt(0) - s1.charAt(0)) + 1) + Math.min(s0.charAt(0), s1.charAt(0))))); }));
        registry.registerExpression("a random character from %object% and %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof java.lang.String s0) || !(a1 instanceof java.lang.String s1) || s0.isEmpty() || s1.isEmpty() ? null : String.valueOf((char)(java.util.concurrent.ThreadLocalRandom.current().nextInt(Math.abs(s0.charAt(0) - s1.charAt(0)) + 1) + Math.min(s0.charAt(0), s1.charAt(0))))); }));
        registry.registerExpression("a random character between %object% to %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof java.lang.String s0) || !(a1 instanceof java.lang.String s1) || s0.isEmpty() || s1.isEmpty() ? null : String.valueOf((char)(java.util.concurrent.ThreadLocalRandom.current().nextInt(Math.abs(s0.charAt(0) - s1.charAt(0)) + 1) + Math.min(s0.charAt(0), s1.charAt(0))))); }));
        registry.registerExpression("a random character between %object% and %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof java.lang.String s0) || !(a1 instanceof java.lang.String s1) || s0.isEmpty() || s1.isEmpty() ? null : String.valueOf((char)(java.util.concurrent.ThreadLocalRandom.current().nextInt(Math.abs(s0.charAt(0) - s1.charAt(0)) + 1) + Math.min(s0.charAt(0), s1.charAt(0))))); }));
        registry.registerExpression("%location% offset by [[the] vectors] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.Location l) || !(a1 instanceof org.bukkit.util.Vector v) ? null : l.clone().add(v)); }));
        registry.registerExpression("%location%[ ]~[~][ ]%object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.Location l) || !(a1 instanceof org.bukkit.util.Vector v) ? null : l.clone().add(v)); }));
        registry.registerExpression("[the] break speed[s] [of %object%] [for %object%]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.block.Block b) || !(a1 instanceof org.bukkit.entity.Player p) ? null : b.getBreakSpeed(p)); }));
        registry.registerExpression("%object%'[s] break speed[s] [for %object%]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.block.Block b) || !(a1 instanceof org.bukkit.entity.Player p) ? null : b.getBreakSpeed(p)); }));
        registry.registerExpression("%object% with [a] yaw [of] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.Location loc) || !(a1 instanceof java.lang.Number n) ? null : new org.bukkit.Location(loc.getWorld(), loc.getX(), loc.getY(), loc.getZ(), n.floatValue(), loc.getPitch())); }));
        registry.registerExpression("%object% with [a] pitch [of] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.Location loc) || !(a1 instanceof java.lang.Number n) ? null : new org.bukkit.Location(loc.getWorld(), loc.getX(), loc.getY(), loc.getZ(), loc.getYaw(), n.floatValue())); }));
        registry.registerExpression("%object% with [a] yaw [of] %object% and [a] pitch [of] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return (!(a0 instanceof org.bukkit.Location loc) || !(a1 instanceof java.lang.Number ny) || !(a2 instanceof java.lang.Number np) ? null : new org.bukkit.Location(loc.getWorld(), loc.getX(), loc.getY(), loc.getZ(), ny.floatValue(), np.floatValue())); }));
        registry.registerExpression("[a] [new] vector [(from|at|to)] %object%,[ ]%object%(,[ ]| and )%object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return (!(a0 instanceof java.lang.Number x) || !(a1 instanceof java.lang.Number y) || !(a2 instanceof java.lang.Number z) ? null : new org.bukkit.util.Vector(x.doubleValue(), y.doubleValue(), z.doubleValue())); }));
        registry.registerExpression("[the] angle between [[the] vectors] %object% and %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.util.Vector v0) || !(a1 instanceof org.bukkit.util.Vector v1) ? null : (v0.angle(v1) * (float) (180.0 / Math.PI))); }));
        registry.registerExpression("%object% percent of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof Number n0) || !(a1 instanceof Number n1) ? null : n1.doubleValue() * n0.doubleValue() / 100.0); }));
        registry.registerExpression("%object% (otherwise|?) %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (a0 != null ? a0 : a1); }));
        registry.registerExpression("%object% cross %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.util.Vector v0) || !(a1 instanceof org.bukkit.util.Vector v1) ? null : v0.clone().crossProduct(v1)); }));
        registry.registerExpression("[the] (location|position) [at] [\\(][x[ ][=[ ]]]%object%, [y[ ][=[ ]]]%object%, [and] [z[ ][=[ ]]]%object%[\\)] [[(in|of) [[the] world]] %object%]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); Object a3 = a.get(3).getSingle(ctx); return (!(a0 instanceof java.lang.Number nx) || !(a1 instanceof java.lang.Number ny) || !(a2 instanceof java.lang.Number nz) || !(a3 instanceof org.bukkit.World w) ? null : new org.bukkit.Location(w, nx.doubleValue(), ny.doubleValue(), nz.doubleValue())); }));
        registry.registerExpression("[a] [new] chest inventory (named|with name) %object% [with %object% row[s]]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (org.bukkit.Bukkit.createInventory(null, java.lang.Math.max(0, java.lang.Math.min(54, (a1 instanceof java.lang.Number rn ? rn.intValue()*9 : 27))), (a0 instanceof net.kyori.adventure.text.Component nm ? nm : org.bukkit.event.inventory.InventoryType.CHEST.defaultTitle()))); }));
        registry.registerExpression("[a] [new] chest inventory with %object% row[s] [(named|with name) %object%]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (org.bukkit.Bukkit.createInventory(null, java.lang.Math.max(0, java.lang.Math.min(54, (a0 instanceof java.lang.Number rn ? rn.intValue()*9 : 27))), (a1 instanceof net.kyori.adventure.text.Component nm ? nm : org.bukkit.event.inventory.InventoryType.CHEST.defaultTitle()))); }));
        registry.registerExpression("%object% to location in %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.util.Vector v) || !(a1 instanceof org.bukkit.World w) ? null : v.toLocation(w)); }));
        registry.registerExpression("location from %object% in %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.util.Vector v) || !(a1 instanceof org.bukkit.World w) ? null : v.toLocation(w)); }));
        registry.registerExpression("location of %object% in %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.util.Vector v) || !(a1 instanceof org.bukkit.World w) ? null : v.toLocation(w)); }));
        registry.registerExpression("%object% [to location] in %object% with yaw %object% and pitch %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); Object a3 = a.get(3).getSingle(ctx); return (!(a0 instanceof org.bukkit.util.Vector v) || !(a1 instanceof org.bukkit.World w) || !(a2 instanceof java.lang.Number y) || !(a3 instanceof java.lang.Number p) ? null : v.toLocation(w, y.floatValue(), p.floatValue())); }));
        registry.registerExpression("location from %object% in %object% with yaw %object% and pitch %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); Object a3 = a.get(3).getSingle(ctx); return (!(a0 instanceof org.bukkit.util.Vector v) || !(a1 instanceof org.bukkit.World w) || !(a2 instanceof java.lang.Number y) || !(a3 instanceof java.lang.Number p) ? null : v.toLocation(w, y.floatValue(), p.floatValue())); }));
        registry.registerExpression("location of %object% in %object% with yaw %object% and pitch %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); Object a3 = a.get(3).getSingle(ctx); return (!(a0 instanceof org.bukkit.util.Vector v) || !(a1 instanceof org.bukkit.World w) || !(a2 instanceof java.lang.Number y) || !(a3 instanceof java.lang.Number p) ? null : v.toLocation(w, y.floatValue(), p.floatValue())); }));
    }
}
