package co.xenastudios.neoskript.lang;

import co.xenastudios.neoskript.api.syntax.Expression;
import co.xenastudios.neoskript.api.registry.SyntaxRegistry;
import co.xenastudios.neoskript.core.expression.ComputedExpression;
import co.xenastudios.neoskript.core.expression.ComputedListExpression;

/** Generated unified expressions (0-4 inputs, source-grounded). One per line for compile-drop. */
public final class GenExprUnified {
    private GenExprUnified() {}

    public static void register(SyntaxRegistry registry) {
        registry.registerExpression("%object%'s [elapsed] (item|tool) us[ag]e time", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.entity.LivingEntity ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(((org.bukkit.entity.LivingEntity) a0).getHandRaisedTime()) : null); }));
        registry.registerExpression("%object%'s remaining (item|tool) us[ag]e time", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.entity.LivingEntity ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(((org.bukkit.entity.LivingEntity) a0).getItemUseRemainingTime()) : null); }));
        registry.registerExpression("[the] (amount|number) of %object% (in|of) %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof org.bukkit.inventory.ItemStack && a1 instanceof org.bukkit.inventory.Inventory) ? Long.valueOf(java.util.Arrays.stream(((org.bukkit.inventory.Inventory) a1).getContents()).filter(java.util.Objects::nonNull).filter(it -> it.isSimilar((org.bukkit.inventory.ItemStack) a0)).mapToLong(org.bukkit.inventory.ItemStack::getAmount).sum()) : null); }));
        registry.registerExpression("[an] eternity", Object.class, a -> new ComputedExpression(ctx -> {  return (co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(Long.MAX_VALUE)); }));
        registry.registerExpression("forever", Object.class, a -> new ComputedExpression(ctx -> {  return (co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(Long.MAX_VALUE)); }));
        registry.registerExpression("[an] (indefinite|infinite) (duration|timespan)", Object.class, a -> new ComputedExpression(ctx -> {  return (co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(Long.MAX_VALUE)); }));


        registry.registerExpression("[a] %object% colo[u]red %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof org.bukkit.block.banner.PatternType && a1 instanceof org.bukkit.DyeColor) ? new org.bukkit.block.banner.Pattern((org.bukkit.DyeColor) a1, (org.bukkit.block.banner.PatternType) a0) : null); }));

        registry.registerExpression("primary [beacon] effect of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return ((a0 instanceof org.bukkit.block.Block && ((org.bukkit.block.Block) a0).getState() instanceof org.bukkit.block.Beacon && ((org.bukkit.block.Beacon) ((org.bukkit.block.Block) a0).getState()).getPrimaryEffect() != null) ? ((org.bukkit.block.Beacon) ((org.bukkit.block.Block) a0).getState()).getPrimaryEffect().getType() : null); }));
        registry.registerExpression("secondary [beacon] effect of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return ((a0 instanceof org.bukkit.block.Block && ((org.bukkit.block.Block) a0).getState() instanceof org.bukkit.block.Beacon && ((org.bukkit.block.Beacon) ((org.bukkit.block.Block) a0).getState()).getSecondaryEffect() != null) ? ((org.bukkit.block.Beacon) ((org.bukkit.block.Block) a0).getState()).getSecondaryEffect().getType() : null); }));





        registry.registerExpression("[the] main command [label|name] [of [[the] command[s] %object%]]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (((java.util.function.Function<org.bukkit.command.Command,String>)(c -> c == null ? null : c.getName())).apply(a0 instanceof String ? org.bukkit.Bukkit.getServer().getCommandMap().getCommand((String) a0) : null)); }));
        registry.registerExpression("[the] description [of [[the] command[s] %object%]]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (((java.util.function.Function<org.bukkit.command.Command,String>)(c -> c == null ? null : c.getDescription())).apply(a0 instanceof String ? org.bukkit.Bukkit.getServer().getCommandMap().getCommand((String) a0) : null)); }));
        registry.registerExpression("[the] label [of [[the] command[s] %object%]]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (((java.util.function.Function<org.bukkit.command.Command,String>)(c -> c == null ? null : c.getLabel())).apply(a0 instanceof String ? org.bukkit.Bukkit.getServer().getCommandMap().getCommand((String) a0) : null)); }));
        registry.registerExpression("[the] usage [of [[the] command[s] %object%]]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (((java.util.function.Function<org.bukkit.command.Command,String>)(c -> c == null ? null : c.getUsage())).apply(a0 instanceof String ? org.bukkit.Bukkit.getServer().getCommandMap().getCommand((String) a0) : null)); }));
        registry.registerExpression("[(all|the|all [of] the)] aliases [of [[the] command[s] %object%]]", Object.class, a -> new ComputedListExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object _c = (((java.util.function.Function<org.bukkit.command.Command,java.util.List<String>>)(c -> c == null ? null : c.getAliases())).apply(a0 instanceof String ? org.bukkit.Bukkit.getServer().getCommandMap().getCommand((String) a0) : null)); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] permission [of [[the] command[s] %object%]]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (((java.util.function.Function<org.bukkit.command.Command,String>)(c -> c == null ? null : c.getPermission())).apply(a0 instanceof String ? org.bukkit.Bukkit.getServer().getCommandMap().getCommand((String) a0) : null)); }));
        registry.registerExpression("[the] permission message [of [[the] command[s] %object%]]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (((java.util.function.Function<org.bukkit.command.Command,String>)(c -> c == null ? null : c.getPermissionMessage())).apply(a0 instanceof String ? org.bukkit.Bukkit.getServer().getCommandMap().getCommand((String) a0) : null)); }));
        registry.registerExpression("[the] plugin [owner] [of [[the] command[s] %object%]]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (((java.util.function.Function<org.bukkit.command.Command,String>)(c -> c == null ? null : c instanceof org.bukkit.command.PluginCommand ? ((org.bukkit.command.PluginCommand) c).getPlugin().getName() : c instanceof org.bukkit.command.defaults.BukkitCommand ? "Bukkit" : c.getClass().getPackage().getName().startsWith("org.spigot") ? "Spigot" : c.getClass().getPackage().getName().startsWith("com.destroystokyo.paper") ? "Paper" : "Unknown")).apply(a0 instanceof String ? org.bukkit.Bukkit.getServer().getCommandMap().getCommand((String) a0) : null)); }));
        registry.registerExpression("%object% with (damage|data) [value] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof org.bukkit.inventory.ItemStack && a1 instanceof Number) ? java.util.stream.Stream.of(((org.bukkit.inventory.ItemStack) a0).clone()).peek(_i -> _i.setDurability((short) ((Number) a1).intValue())).findFirst().orElse(null) : null); }));
        registry.registerExpression("%object% damaged by %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof org.bukkit.inventory.ItemStack && a1 instanceof Number) ? java.util.stream.Stream.of(((org.bukkit.inventory.ItemStack) a0).clone()).peek(_i -> _i.setDurability((short) ((Number) a1).intValue())).findFirst().orElse(null) : null); }));
        registry.registerExpression("interpolation delay[s] of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.entity.Display ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks((long) ((org.bukkit.entity.Display) a0).getInterpolationDelay()) : null); }));
        registry.registerExpression("interpolation duration[s] of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.entity.Display ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks((long) ((org.bukkit.entity.Display) a0).getInterpolationDuration()) : null); }));













        registry.registerExpression("exact item[s] of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (!(a0 instanceof org.bukkit.block.Block) || !((org.bukkit.block.Block) a0).getType().isItem() ? null : java.util.stream.Stream.of(new org.bukkit.inventory.ItemStack(((org.bukkit.block.Block) a0).getType())).peek(s -> s.editMeta(org.bukkit.inventory.meta.BlockStateMeta.class, m -> m.setBlockState(((org.bukkit.block.Block) a0).getState()))).findFirst().get()); }));
        registry.registerExpression("%object% [firework [effect]] colo[u]red %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.FireworkEffect.Type) || !((a1 instanceof java.util.Collection && !((java.util.Collection<?>) a1).isEmpty()) || (a1 instanceof Object[] && ((Object[]) a1).length > 0) || a1 instanceof org.bukkit.Color) ? null : org.bukkit.FireworkEffect.builder().with((org.bukkit.FireworkEffect.Type) a0).withColor((java.lang.Iterable<?>) (a1 instanceof java.util.Collection ? (java.util.Collection<?>) a1 : a1 instanceof Object[] ? java.util.Arrays.asList((Object[]) a1) : java.util.List.of(a1))).flicker(false).trail(false).build()); }));
        registry.registerExpression("flickering %object% [firework [effect]] colo[u]red %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.FireworkEffect.Type) || !((a1 instanceof java.util.Collection && !((java.util.Collection<?>) a1).isEmpty()) || (a1 instanceof Object[] && ((Object[]) a1).length > 0) || a1 instanceof org.bukkit.Color) ? null : org.bukkit.FireworkEffect.builder().with((org.bukkit.FireworkEffect.Type) a0).withColor((java.lang.Iterable<?>) (a1 instanceof java.util.Collection ? (java.util.Collection<?>) a1 : a1 instanceof Object[] ? java.util.Arrays.asList((Object[]) a1) : java.util.List.of(a1))).flicker(true).trail(false).build()); }));
        registry.registerExpression("trailing %object% [firework [effect]] colo[u]red %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.FireworkEffect.Type) || !((a1 instanceof java.util.Collection && !((java.util.Collection<?>) a1).isEmpty()) || (a1 instanceof Object[] && ((Object[]) a1).length > 0) || a1 instanceof org.bukkit.Color) ? null : org.bukkit.FireworkEffect.builder().with((org.bukkit.FireworkEffect.Type) a0).withColor((java.lang.Iterable<?>) (a1 instanceof java.util.Collection ? (java.util.Collection<?>) a1 : a1 instanceof Object[] ? java.util.Arrays.asList((Object[]) a1) : java.util.List.of(a1))).flicker(false).trail(true).build()); }));
        registry.registerExpression("flickering trailing %object% [firework [effect]] colo[u]red %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.FireworkEffect.Type) || !((a1 instanceof java.util.Collection && !((java.util.Collection<?>) a1).isEmpty()) || (a1 instanceof Object[] && ((Object[]) a1).length > 0) || a1 instanceof org.bukkit.Color) ? null : org.bukkit.FireworkEffect.builder().with((org.bukkit.FireworkEffect.Type) a0).withColor((java.lang.Iterable<?>) (a1 instanceof java.util.Collection ? (java.util.Collection<?>) a1 : a1 instanceof Object[] ? java.util.Arrays.asList((Object[]) a1) : java.util.List.of(a1))).flicker(true).trail(true).build()); }));
        registry.registerExpression("trailing flickering %object% [firework [effect]] colo[u]red %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a0 instanceof org.bukkit.FireworkEffect.Type) || !((a1 instanceof java.util.Collection && !((java.util.Collection<?>) a1).isEmpty()) || (a1 instanceof Object[] && ((Object[]) a1).length > 0) || a1 instanceof org.bukkit.Color) ? null : org.bukkit.FireworkEffect.builder().with((org.bukkit.FireworkEffect.Type) a0).withColor((java.lang.Iterable<?>) (a1 instanceof java.util.Collection ? (java.util.Collection<?>) a1 : a1 instanceof Object[] ? java.util.Arrays.asList((Object[]) a1) : java.util.List.of(a1))).flicker(true).trail(true).build()); }));
        registry.registerExpression("%object% [firework [effect]] colo[u]red %object% fad(e|ing) [to] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return (!(a0 instanceof org.bukkit.FireworkEffect.Type) || !((a1 instanceof java.util.Collection && !((java.util.Collection<?>) a1).isEmpty()) || (a1 instanceof Object[] && ((Object[]) a1).length > 0) || a1 instanceof org.bukkit.Color) || !((a2 instanceof java.util.Collection && !((java.util.Collection<?>) a2).isEmpty()) || (a2 instanceof Object[] && ((Object[]) a2).length > 0) || a2 instanceof org.bukkit.Color) ? null : org.bukkit.FireworkEffect.builder().with((org.bukkit.FireworkEffect.Type) a0).withColor((java.lang.Iterable<?>) (a1 instanceof java.util.Collection ? (java.util.Collection<?>) a1 : a1 instanceof Object[] ? java.util.Arrays.asList((Object[]) a1) : java.util.List.of(a1))).withFade((java.lang.Iterable<?>) (a2 instanceof java.util.Collection ? (java.util.Collection<?>) a2 : a2 instanceof Object[] ? java.util.Arrays.asList((Object[]) a2) : java.util.List.of(a2))).flicker(false).trail(false).build()); }));
        registry.registerExpression("flickering %object% [firework [effect]] colo[u]red %object% fad(e|ing) [to] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return (!(a0 instanceof org.bukkit.FireworkEffect.Type) || !((a1 instanceof java.util.Collection && !((java.util.Collection<?>) a1).isEmpty()) || (a1 instanceof Object[] && ((Object[]) a1).length > 0) || a1 instanceof org.bukkit.Color) || !((a2 instanceof java.util.Collection && !((java.util.Collection<?>) a2).isEmpty()) || (a2 instanceof Object[] && ((Object[]) a2).length > 0) || a2 instanceof org.bukkit.Color) ? null : org.bukkit.FireworkEffect.builder().with((org.bukkit.FireworkEffect.Type) a0).withColor((java.lang.Iterable<?>) (a1 instanceof java.util.Collection ? (java.util.Collection<?>) a1 : a1 instanceof Object[] ? java.util.Arrays.asList((Object[]) a1) : java.util.List.of(a1))).withFade((java.lang.Iterable<?>) (a2 instanceof java.util.Collection ? (java.util.Collection<?>) a2 : a2 instanceof Object[] ? java.util.Arrays.asList((Object[]) a2) : java.util.List.of(a2))).flicker(true).trail(false).build()); }));
        registry.registerExpression("trailing %object% [firework [effect]] colo[u]red %object% fad(e|ing) [to] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return (!(a0 instanceof org.bukkit.FireworkEffect.Type) || !((a1 instanceof java.util.Collection && !((java.util.Collection<?>) a1).isEmpty()) || (a1 instanceof Object[] && ((Object[]) a1).length > 0) || a1 instanceof org.bukkit.Color) || !((a2 instanceof java.util.Collection && !((java.util.Collection<?>) a2).isEmpty()) || (a2 instanceof Object[] && ((Object[]) a2).length > 0) || a2 instanceof org.bukkit.Color) ? null : org.bukkit.FireworkEffect.builder().with((org.bukkit.FireworkEffect.Type) a0).withColor((java.lang.Iterable<?>) (a1 instanceof java.util.Collection ? (java.util.Collection<?>) a1 : a1 instanceof Object[] ? java.util.Arrays.asList((Object[]) a1) : java.util.List.of(a1))).withFade((java.lang.Iterable<?>) (a2 instanceof java.util.Collection ? (java.util.Collection<?>) a2 : a2 instanceof Object[] ? java.util.Arrays.asList((Object[]) a2) : java.util.List.of(a2))).flicker(false).trail(true).build()); }));
        registry.registerExpression("flickering trailing %object% [firework [effect]] colo[u]red %object% fad(e|ing) [to] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return (!(a0 instanceof org.bukkit.FireworkEffect.Type) || !((a1 instanceof java.util.Collection && !((java.util.Collection<?>) a1).isEmpty()) || (a1 instanceof Object[] && ((Object[]) a1).length > 0) || a1 instanceof org.bukkit.Color) || !((a2 instanceof java.util.Collection && !((java.util.Collection<?>) a2).isEmpty()) || (a2 instanceof Object[] && ((Object[]) a2).length > 0) || a2 instanceof org.bukkit.Color) ? null : org.bukkit.FireworkEffect.builder().with((org.bukkit.FireworkEffect.Type) a0).withColor((java.lang.Iterable<?>) (a1 instanceof java.util.Collection ? (java.util.Collection<?>) a1 : a1 instanceof Object[] ? java.util.Arrays.asList((Object[]) a1) : java.util.List.of(a1))).withFade((java.lang.Iterable<?>) (a2 instanceof java.util.Collection ? (java.util.Collection<?>) a2 : a2 instanceof Object[] ? java.util.Arrays.asList((Object[]) a2) : java.util.List.of(a2))).flicker(true).trail(true).build()); }));
        registry.registerExpression("trailing flickering %object% [firework [effect]] colo[u]red %object% fad(e|ing) [to] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return (!(a0 instanceof org.bukkit.FireworkEffect.Type) || !((a1 instanceof java.util.Collection && !((java.util.Collection<?>) a1).isEmpty()) || (a1 instanceof Object[] && ((Object[]) a1).length > 0) || a1 instanceof org.bukkit.Color) || !((a2 instanceof java.util.Collection && !((java.util.Collection<?>) a2).isEmpty()) || (a2 instanceof Object[] && ((Object[]) a2).length > 0) || a2 instanceof org.bukkit.Color) ? null : org.bukkit.FireworkEffect.builder().with((org.bukkit.FireworkEffect.Type) a0).withColor((java.lang.Iterable<?>) (a1 instanceof java.util.Collection ? (java.util.Collection<?>) a1 : a1 instanceof Object[] ? java.util.Arrays.asList((Object[]) a1) : java.util.List.of(a1))).withFade((java.lang.Iterable<?>) (a2 instanceof java.util.Collection ? (java.util.Collection<?>) a2 : a2 instanceof Object[] ? java.util.Arrays.asList((Object[]) a2) : java.util.List.of(a2))).flicker(true).trail(true).build()); }));
        registry.registerExpression("%object% formatted [human-readable]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof java.util.Date ? new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss z").format((java.util.Date) a0) : null); }));
        registry.registerExpression("[human-readable] formatted %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof java.util.Date ? new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss z").format((java.util.Date) a0) : null); }));
        registry.registerExpression("%object% formatted [human-readable] (with|as) %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof java.util.Date && a1 instanceof String) ? new java.text.SimpleDateFormat((String) a1).format((java.util.Date) a0) : null); }));
        registry.registerExpression("[human-readable] formatted %object% (with|as) %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof java.util.Date && a1 instanceof String) ? new java.text.SimpleDateFormat((String) a1).format((java.util.Date) a0) : null); }));
        registry.registerExpression("[the] [furnace] cook[ing] time [of %object%]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.block.Block b && b.getState() instanceof org.bukkit.block.Furnace f ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(f.getCookTime()) : null); }));
        registry.registerExpression("%object%'[s]cook[ing] time", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.block.Block b && b.getState() instanceof org.bukkit.block.Furnace f ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(f.getCookTime()) : null); }));
        registry.registerExpression("[the] [furnace] total cook[ing] time [of %object%]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.block.Block b && b.getState() instanceof org.bukkit.block.Furnace f ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(f.getCookTimeTotal()) : null); }));
        registry.registerExpression("%object%'[s]total cook[ing] time", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.block.Block b && b.getState() instanceof org.bukkit.block.Furnace f ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(f.getCookTimeTotal()) : null); }));
        registry.registerExpression("[the] [furnace] fuel burn[ing] time [of %object%]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.block.Block b && b.getState() instanceof org.bukkit.block.Furnace f ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(f.getBurnTime()) : null); }));
        registry.registerExpression("%object%'[s]fuel burn[ing] time", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.block.Block b && b.getState() instanceof org.bukkit.block.Furnace f ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(f.getBurnTime()) : null); }));




        registry.registerExpression("%object% with [a|the] lore %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof org.bukkit.inventory.ItemStack && a1 instanceof String) ? java.util.stream.Stream.of(((org.bukkit.inventory.ItemStack)a0).clone()).map(s -> s.editMeta(m -> m.setLore(java.util.Collections.singletonList((String)a1))) ? s : s).findFirst().orElse(null) : null); }));
        registry.registerExpression("%object% with [entire] tool[ ]tip[s]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.inventory.ItemStack ? java.util.stream.Stream.of(((org.bukkit.inventory.ItemStack)a0).clone()).map(s -> s.editMeta(m -> m.setHideTooltip(false)) ? s : s).findFirst().orElse(null) : null); }));
        registry.registerExpression("%object% without [entire] tool[ ]tip[s]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.inventory.ItemStack ? java.util.stream.Stream.of(((org.bukkit.inventory.ItemStack)a0).clone()).map(s -> s.editMeta(m -> m.setHideTooltip(true)) ? s : s).findFirst().orElse(null) : null); }));
        registry.registerExpression("%object% with additional tool[ ]tip[s]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.inventory.ItemStack ? java.util.stream.Stream.of(((org.bukkit.inventory.ItemStack)a0).clone()).map(s -> s.editMeta(m -> m.removeItemFlags(org.bukkit.inventory.ItemFlag.HIDE_ADDITIONAL_TOOLTIP)) ? s : s).findFirst().orElse(null) : null); }));
        registry.registerExpression("%object% without additional tool[ ]tip[s]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.inventory.ItemStack ? java.util.stream.Stream.of(((org.bukkit.inventory.ItemStack)a0).clone()).map(s -> s.editMeta(m -> m.addItemFlags(org.bukkit.inventory.ItemFlag.HIDE_ADDITIONAL_TOOLTIP)) ? s : s).findFirst().orElse(null) : null); }));
        registry.registerExpression("[all [[of] the]|the] block[[ ]type]s", Object.class, a -> new ComputedListExpression(ctx -> {  Object _c = (java.util.Arrays.stream(org.bukkit.Material.values()).filter(m -> !m.isLegacy() && m.isBlock()).map(org.bukkit.inventory.ItemStack::new).collect(java.util.stream.Collectors.toList())); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("every block[[ ]type]", Object.class, a -> new ComputedListExpression(ctx -> {  Object _c = (java.util.Arrays.stream(org.bukkit.Material.values()).filter(m -> !m.isLegacy() && m.isBlock()).map(org.bukkit.inventory.ItemStack::new).collect(java.util.stream.Collectors.toList())); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[all [[of] the]|the|every] block[s] of type[s] %object%", Object.class, a -> new ComputedListExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object _c = (a0 instanceof org.bukkit.inventory.ItemStack ? (((org.bukkit.inventory.ItemStack)a0).getType().isBlock() ? java.util.List.of(((org.bukkit.inventory.ItemStack)a0).clone()) : java.util.List.of()) : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[all [[of] the]|the|every] item[s] of type[s] %object%", Object.class, a -> new ComputedListExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object _c = (a0 instanceof org.bukkit.inventory.ItemStack ? java.util.List.of(((org.bukkit.inventory.ItemStack)a0).clone()) : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] last attacker of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (!(a0 instanceof org.bukkit.entity.Entity ent) || !(ent.getLastDamageCause() instanceof org.bukkit.event.entity.EntityDamageByEntityEvent ev) ? null : (ev.getDamager() instanceof org.bukkit.entity.Projectile pr && pr.getShooter() instanceof org.bukkit.entity.Entity sh ? sh : ev.getDamager())); }));
        registry.registerExpression("[the] loot of %object% (with|using) [[loot] context] %object%", Object.class, a -> new ComputedListExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object _c = ((a0 instanceof org.bukkit.loot.LootTable && a1 instanceof org.bukkit.loot.LootContext) ? ((org.bukkit.loot.LootTable) a0).populateLoot(java.util.concurrent.ThreadLocalRandom.current(), (org.bukkit.loot.LootContext) a1) : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] loot of %object%", Object.class, a -> new ComputedListExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object _c = ((a0 instanceof org.bukkit.loot.LootTable) ? ((org.bukkit.loot.LootTable) a0).populateLoot(java.util.concurrent.ThreadLocalRandom.current(), new org.bukkit.loot.LootContext.Builder(org.bukkit.Bukkit.getWorlds().get(0).getSpawnLocation()).build()) : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("%object%'[s] loot (with|using) [[loot] context] %object%", Object.class, a -> new ComputedListExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object _c = ((a0 instanceof org.bukkit.loot.LootTable && a1 instanceof org.bukkit.loot.LootContext) ? ((org.bukkit.loot.LootTable) a0).populateLoot(java.util.concurrent.ThreadLocalRandom.current(), (org.bukkit.loot.LootContext) a1) : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("%object%'[s] loot", Object.class, a -> new ComputedListExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object _c = ((a0 instanceof org.bukkit.loot.LootTable) ? ((org.bukkit.loot.LootTable) a0).populateLoot(java.util.concurrent.ThreadLocalRandom.current(), new org.bukkit.loot.LootContext.Builder(org.bukkit.Bukkit.getWorlds().get(0).getSpawnLocation()).build()) : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] love[d] time of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.entity.Animals ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(((org.bukkit.entity.Animals) a0).getLoveModeTicks()) : (a0 instanceof org.bukkit.entity.LivingEntity ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(0L) : null)); }));
        registry.registerExpression("%object%'[s] love[d] time", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.entity.Animals ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(((org.bukkit.entity.Animals) a0).getLoveModeTicks()) : (a0 instanceof org.bukkit.entity.LivingEntity ? co.xenastudios.neoskript.core.runtime.Timespan.ofTicks(0L) : null)); }));
        registry.registerExpression("metadata [(value|tag)[s]] %object% of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof String && a1 instanceof org.bukkit.metadata.Metadatable && !((org.bukkit.metadata.Metadatable) a1).getMetadata((String) a0).isEmpty()) ? ((org.bukkit.metadata.Metadatable) a1).getMetadata((String) a0).get(((org.bukkit.metadata.Metadatable) a1).getMetadata((String) a0).size() - 1).value() : null); }));
        registry.registerExpression("%object%'[s] metadata [(value|tag)[s]] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a1 instanceof String && a0 instanceof org.bukkit.metadata.Metadatable && !((org.bukkit.metadata.Metadatable) a0).getMetadata((String) a1).isEmpty()) ? ((org.bukkit.metadata.Metadatable) a0).getMetadata((String) a1).get(((org.bukkit.metadata.Metadatable) a0).getMetadata((String) a1).size() - 1).value() : null); }));
        registry.registerExpression("[a[n]] potion effect of %object% [[of tier] %object%] [for %object%]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return ((a0 instanceof org.bukkit.potion.PotionEffectType && a2 instanceof co.xenastudios.neoskript.core.runtime.Timespan && (a1 == null || a1 instanceof Number)) ? new org.bukkit.potion.PotionEffect((org.bukkit.potion.PotionEffectType) a0, (int) Math.max(0L, Math.min(((co.xenastudios.neoskript.core.runtime.Timespan) a2).ticks(), (long) Integer.MAX_VALUE)), a1 == null ? 0 : ((Number) a1).intValue() - 1, false, true, true) : null); }));
        registry.registerExpression("[a[n]] ambient potion effect of %object% [[of tier] %object%] [for %object%]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return ((a0 instanceof org.bukkit.potion.PotionEffectType && a2 instanceof co.xenastudios.neoskript.core.runtime.Timespan && (a1 == null || a1 instanceof Number)) ? new org.bukkit.potion.PotionEffect((org.bukkit.potion.PotionEffectType) a0, (int) Math.max(0L, Math.min(((co.xenastudios.neoskript.core.runtime.Timespan) a2).ticks(), (long) Integer.MAX_VALUE)), a1 == null ? 0 : ((Number) a1).intValue() - 1, true, true, true) : null); }));
        registry.registerExpression("[an] (infinite|permanent) potion effect of %object% [[of tier] %object%]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof org.bukkit.potion.PotionEffectType && (a1 == null || a1 instanceof Number)) ? new org.bukkit.potion.PotionEffect((org.bukkit.potion.PotionEffectType) a0, -1, a1 == null ? 0 : ((Number) a1).intValue() - 1, false, true, true) : null); }));
        registry.registerExpression("[an] (infinite|permanent) ambient potion effect of %object% [[of tier] %object%]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof org.bukkit.potion.PotionEffectType && (a1 == null || a1 instanceof Number)) ? new org.bukkit.potion.PotionEffect((org.bukkit.potion.PotionEffectType) a0, -1, a1 == null ? 0 : ((Number) a1).intValue() - 1, true, true, true) : null); }));
        registry.registerExpression("[an] (infinite|permanent) %object% [[of tier] %object%] [potion [effect]]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof org.bukkit.potion.PotionEffectType && (a1 == null || a1 instanceof Number)) ? new org.bukkit.potion.PotionEffect((org.bukkit.potion.PotionEffectType) a0, -1, a1 == null ? 0 : ((Number) a1).intValue() - 1, false, true, true) : null); }));
        registry.registerExpression("[an] (infinite|permanent) ambient %object% [[of tier] %object%] [potion [effect]]", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof org.bukkit.potion.PotionEffectType && (a1 == null || a1 instanceof Number)) ? new org.bukkit.potion.PotionEffect((org.bukkit.potion.PotionEffectType) a0, -1, a1 == null ? 0 : ((Number) a1).intValue() - 1, true, true, true) : null); }));
        registry.registerExpression("[a] potion effect [of %object%] (from|using|based on) %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (!(a1 instanceof org.bukkit.potion.PotionEffect) ? null : (a0 == null ? (org.bukkit.potion.PotionEffect) a1 : (a0 instanceof org.bukkit.potion.PotionEffectType ? new org.bukkit.potion.PotionEffect((org.bukkit.potion.PotionEffectType) a0, ((org.bukkit.potion.PotionEffect) a1).getDuration(), ((org.bukkit.potion.PotionEffect) a1).getAmplifier(), ((org.bukkit.potion.PotionEffect) a1).isAmbient(), ((org.bukkit.potion.PotionEffect) a1).hasParticles(), ((org.bukkit.potion.PotionEffect) a1).hasIcon()) : null))); }));
        registry.registerExpression("[(all [[of] the]|the)] numbers (between|from) %object% (and|to) %object%", Object.class, a -> new ComputedListExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object _c = ((a0 instanceof Number && a1 instanceof Number) ? java.util.stream.IntStream.range(0, (int) Math.floor(Math.abs(((Number) a1).doubleValue() - ((Number) a0).doubleValue()) + 1)).mapToObj(k -> (Number) Double.valueOf(Math.min(((Number) a0).doubleValue(), ((Number) a1).doubleValue()) + (((Number) a0).doubleValue() > ((Number) a1).doubleValue() ? (int) Math.floor(Math.abs(((Number) a1).doubleValue() - ((Number) a0).doubleValue()) + 1) - 1 - k : k))).toArray(Number[]::new) : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[(all [[of] the]|the)] integers (between|from) %object% (and|to) %object%", Object.class, a -> new ComputedListExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object _c = ((a0 instanceof Number && a1 instanceof Number) ? java.util.stream.IntStream.range(0, (int) (Math.floor(Math.max(((Number) a0).doubleValue(), ((Number) a1).doubleValue())) - Math.ceil(Math.min(((Number) a0).doubleValue(), ((Number) a1).doubleValue())) + 1)).mapToObj(k -> (Number) Long.valueOf((long) Math.ceil(Math.min(((Number) a0).doubleValue(), ((Number) a1).doubleValue())) + (((Number) a0).doubleValue() > ((Number) a1).doubleValue() ? (int) (Math.floor(Math.max(((Number) a0).doubleValue(), ((Number) a1).doubleValue())) - Math.ceil(Math.min(((Number) a0).doubleValue(), ((Number) a1).doubleValue())) + 1) - 1 - k : k))).toArray(Number[]::new) : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[a[n]] (plain|unmodified) %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.inventory.ItemStack ? new org.bukkit.inventory.ItemStack(((org.bukkit.inventory.ItemStack) a0).getType(), ((org.bukkit.inventory.ItemStack) a0).getAmount()) : null); }));
        registry.registerExpression("skull of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return ((a0 instanceof org.bukkit.OfflinePlayer op) ? java.util.stream.Stream.of(new org.bukkit.inventory.ItemStack(org.bukkit.Material.PLAYER_HEAD)).peek(it -> it.editMeta(org.bukkit.inventory.meta.SkullMeta.class, m -> m.setOwningPlayer(op))).findFirst().orElse(null) : null); }));
        registry.registerExpression("active %object% [potion] effect of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a1 instanceof org.bukkit.entity.LivingEntity le && a0 instanceof org.bukkit.potion.PotionEffectType pet) ? le.getPotionEffect(pet) : null); }));
        registry.registerExpression("(raw|minecraft|vanilla) name[s] of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return ((a0 instanceof org.bukkit.inventory.ItemStack is) ? is.getType().getKey().toString() : null); }));
        registry.registerExpression("%object% rotated around [the] [global] x(-| )axis by %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (a1 instanceof Number __n && !Double.isInfinite(__n.doubleValue()*Math.PI/180d) && !Double.isNaN(__n.doubleValue()*Math.PI/180d) ? (a0 instanceof org.bukkit.util.Vector __v ? (Object) __v.clone().rotateAroundX(__n.doubleValue()*Math.PI/180d) : (a0 instanceof org.joml.Quaternionf __q ? (Object) __q.rotateLocalX((float)(__n.doubleValue()*Math.PI/180d), new org.joml.Quaternionf()) : null)) : null); }));
        registry.registerExpression("%object% rotated around [the] [global] y(-| )axis by %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (a1 instanceof Number __n && !Double.isInfinite(__n.doubleValue()*Math.PI/180d) && !Double.isNaN(__n.doubleValue()*Math.PI/180d) ? (a0 instanceof org.bukkit.util.Vector __v ? (Object) __v.clone().rotateAroundY(__n.doubleValue()*Math.PI/180d) : (a0 instanceof org.joml.Quaternionf __q ? (Object) __q.rotateLocalY((float)(__n.doubleValue()*Math.PI/180d), new org.joml.Quaternionf()) : null)) : null); }));
        registry.registerExpression("%object% rotated around [the] [global] z(-| )axis by %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (a1 instanceof Number __n && !Double.isInfinite(__n.doubleValue()*Math.PI/180d) && !Double.isNaN(__n.doubleValue()*Math.PI/180d) ? (a0 instanceof org.bukkit.util.Vector __v ? (Object) __v.clone().rotateAroundZ(__n.doubleValue()*Math.PI/180d) : (a0 instanceof org.joml.Quaternionf __q ? (Object) __q.rotateLocalZ((float)(__n.doubleValue()*Math.PI/180d), new org.joml.Quaternionf()) : null)) : null); }));
        registry.registerExpression("%object% rotated around [the|its|their] local x(-| )ax(i|e)s by %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (a0 instanceof org.joml.Quaternionf __q && a1 instanceof Number __n && !Double.isInfinite(__n.doubleValue()*Math.PI/180d) && !Double.isNaN(__n.doubleValue()*Math.PI/180d) ? __q.rotateX((float)(__n.doubleValue()*Math.PI/180d), new org.joml.Quaternionf()) : null); }));
        registry.registerExpression("%object% rotated around [the|its|their] local y(-| )ax(i|e)s by %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (a0 instanceof org.joml.Quaternionf __q && a1 instanceof Number __n && !Double.isInfinite(__n.doubleValue()*Math.PI/180d) && !Double.isNaN(__n.doubleValue()*Math.PI/180d) ? __q.rotateY((float)(__n.doubleValue()*Math.PI/180d), new org.joml.Quaternionf()) : null); }));
        registry.registerExpression("%object% rotated around [the|its|their] local z(-| )ax(i|e)s by %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return (a0 instanceof org.joml.Quaternionf __q && a1 instanceof Number __n && !Double.isInfinite(__n.doubleValue()*Math.PI/180d) && !Double.isNaN(__n.doubleValue()*Math.PI/180d) ? __q.rotateZ((float)(__n.doubleValue()*Math.PI/180d), new org.joml.Quaternionf()) : null); }));
        registry.registerExpression("%object% rotated around [the] %object% by %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return (a2 instanceof Number __n && a1 instanceof org.bukkit.util.Vector __ax && !__ax.isZero() && !Double.isInfinite(__n.doubleValue()*Math.PI/180d) && !Double.isNaN(__n.doubleValue()*Math.PI/180d) ? (a0 instanceof org.bukkit.util.Vector __v ? (Object) __v.clone().rotateAroundNonUnitAxis(__ax.clone().normalize(), __n.doubleValue()*Math.PI/180d) : (a0 instanceof org.joml.Quaternionf __q ? (Object) __q.rotateAxis((float)(__n.doubleValue()*Math.PI/180d), __ax.clone().normalize().toVector3f(), new org.joml.Quaternionf()) : null)) : null); }));
        registry.registerExpression("%object% rotated by x %object%, y %object%(, [and]| and) z %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); Object a3 = a.get(3).getSingle(ctx); return (a0 instanceof org.joml.Quaternionf __q && a1 instanceof Number __x && a2 instanceof Number __y && a3 instanceof Number __z ? new org.joml.Quaternionf(__q).rotateZYX((float)(__z.floatValue()*Math.PI/180), (float)(__y.floatValue()*Math.PI/180), (float)(__x.floatValue()*Math.PI/180)) : null); }));
        registry.registerExpression("ticks of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof co.xenastudios.neoskript.core.runtime.Timespan ? ((co.xenastudios.neoskript.core.runtime.Timespan) a0).millis() / 50L : null); }));
        registry.registerExpression("seconds of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof co.xenastudios.neoskript.core.runtime.Timespan ? ((co.xenastudios.neoskript.core.runtime.Timespan) a0).millis() / 1000L : null); }));
        registry.registerExpression("minutes of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof co.xenastudios.neoskript.core.runtime.Timespan ? ((co.xenastudios.neoskript.core.runtime.Timespan) a0).millis() / 60000L : null); }));
        registry.registerExpression("hours of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof co.xenastudios.neoskript.core.runtime.Timespan ? ((co.xenastudios.neoskript.core.runtime.Timespan) a0).millis() / 3600000L : null); }));
        registry.registerExpression("days of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof co.xenastudios.neoskript.core.runtime.Timespan ? ((co.xenastudios.neoskript.core.runtime.Timespan) a0).millis() / 86400000L : null); }));
        registry.registerExpression("weeks of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof co.xenastudios.neoskript.core.runtime.Timespan ? ((co.xenastudios.neoskript.core.runtime.Timespan) a0).millis() / 604800000L : null); }));
        registry.registerExpression("months of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof co.xenastudios.neoskript.core.runtime.Timespan ? ((co.xenastudios.neoskript.core.runtime.Timespan) a0).millis() / 2592000000L : null); }));
        registry.registerExpression("years of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof co.xenastudios.neoskript.core.runtime.Timespan ? ((co.xenastudios.neoskript.core.runtime.Timespan) a0).millis() / 31536000000L : null); }));
        registry.registerExpression("unbreakable %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.inventory.ItemStack ? ((java.util.function.Function<org.bukkit.inventory.ItemStack, org.bukkit.inventory.ItemStack>) (i -> i.editMeta(m -> m.setUnbreakable(true)) ? i : i)).apply(((org.bukkit.inventory.ItemStack) a0).clone()) : null); }));
        registry.registerExpression("breakable %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.inventory.ItemStack ? ((java.util.function.Function<org.bukkit.inventory.ItemStack, org.bukkit.inventory.ItemStack>) (i -> i.editMeta(m -> m.setUnbreakable(false)) ? i : i)).apply(((org.bukkit.inventory.ItemStack) a0).clone()) : null); }));
        registry.registerExpression("unix timestamp of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return ((a0 instanceof java.util.Date) ? (java.lang.Object) (((java.util.Date) a0).getTime() / 1000.0) : null); }));
        registry.registerExpression("[a] [new] cylindrical vector [from|with] [radius] %object%, [yaw] %object%(,[ and]| and) [height] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return ((a0 instanceof java.lang.Number && a1 instanceof java.lang.Number && a2 instanceof java.lang.Number) ? new org.bukkit.util.Vector(java.lang.Math.abs(((java.lang.Number) a0).doubleValue()) * java.lang.Math.cos((((java.lang.Number) a1).floatValue() > 270f ? ((java.lang.Number) a1).floatValue() - 270f : ((java.lang.Number) a1).floatValue() + 90f) * (java.lang.Math.PI / 180)), ((java.lang.Number) a2).doubleValue(), java.lang.Math.abs(((java.lang.Number) a0).doubleValue()) * java.lang.Math.sin((((java.lang.Number) a1).floatValue() > 270f ? ((java.lang.Number) a1).floatValue() - 270f : ((java.lang.Number) a1).floatValue() + 90f) * (java.lang.Math.PI / 180))) : null); }));
        registry.registerExpression("[a] [new] spherical vector [(from|with)] [radius] %object%, [yaw] %object%(,[ and]| and) [pitch] %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); Object a2 = a.get(2).getSingle(ctx); return ((a0 instanceof java.lang.Number && a1 instanceof java.lang.Number && a2 instanceof java.lang.Number) ? new org.bukkit.util.Vector(java.lang.Math.abs(((java.lang.Number) a0).doubleValue()) * java.lang.Math.sin((((java.lang.Number) a2).floatValue() + 90f) * (java.lang.Math.PI / 180)) * java.lang.Math.cos((((java.lang.Number) a1).floatValue() > 270f ? ((java.lang.Number) a1).floatValue() - 270f : ((java.lang.Number) a1).floatValue() + 90f) * (java.lang.Math.PI / 180)), java.lang.Math.abs(((java.lang.Number) a0).doubleValue()) * java.lang.Math.cos((((java.lang.Number) a2).floatValue() + 90f) * (java.lang.Math.PI / 180)), java.lang.Math.abs(((java.lang.Number) a0).doubleValue()) * java.lang.Math.sin((((java.lang.Number) a2).floatValue() + 90f) * (java.lang.Math.PI / 180)) * java.lang.Math.sin((((java.lang.Number) a1).floatValue() > 270f ? ((java.lang.Number) a1).floatValue() - 270f : ((java.lang.Number) a1).floatValue() + 90f) * (java.lang.Math.PI / 180))) : null); }));
        registry.registerExpression("%object% with fire[ ]resistance", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.inventory.ItemStack ? java.util.Optional.of(((org.bukkit.inventory.ItemStack) a0).clone()).filter(c -> c.editMeta(m -> m.setFireResistant(true))).orElse(null) : null); }));
        registry.registerExpression("%object% without fire[ ]resistance", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.inventory.ItemStack ? java.util.Optional.of(((org.bukkit.inventory.ItemStack) a0).clone()).filter(c -> c.editMeta(m -> m.setFireResistant(false))).orElse(null) : null); }));
        registry.registerExpression("fire resistant %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); return (a0 instanceof org.bukkit.inventory.ItemStack ? java.util.Optional.of(((org.bukkit.inventory.ItemStack) a0).clone()).filter(c -> c.editMeta(m -> m.setFireResistant(true))).orElse(null) : null); }));
        registry.registerExpression("%object% of %object%", Object.class, a -> new ComputedExpression(ctx -> { Object a0 = a.get(0).getSingle(ctx); Object a1 = a.get(1).getSingle(ctx); return ((a0 instanceof Number && a1 instanceof org.bukkit.inventory.ItemStack) ? ((org.bukkit.inventory.ItemStack) a1).asQuantity((int) Math.max(((Number) a0).longValue(), 0L)) : null); }));
    }
}
