package co.xenastudios.neoskript.lang;

import co.xenastudios.neoskript.api.syntax.Expression;
import co.xenastudios.neoskript.api.registry.SyntaxRegistry;
import co.xenastudios.neoskript.core.expression.ComputedExpression;
import co.xenastudios.neoskript.core.expression.ComputedListExpression;

/** Generated bulk expression registration. One registration per line for compile-drop. */
public final class GenExprBulk {
    private GenExprBulk() {}

    public static void register(SyntaxRegistry registry) {
        registry.registerExpression("[(all [[of] the]|the)] permissions (from|of) %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return new Object[0]; java.util.Collection<?> c = (h.getEffectivePermissions().stream().map(org.bukkit.permissions.PermissionAttachmentInfo::getPermission).collect(java.util.stream.Collectors.toSet())); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("target jukebox of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return null; return (h instanceof org.bukkit.entity.Allay ? ((org.bukkit.entity.Allay) h).getJukebox() : null); }); });
        registry.registerExpression("beacon [effect] range of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getState() instanceof org.bukkit.block.Beacon ? ((org.bukkit.block.Beacon) h.getState()).getEffectRange() : null); }); });
        registry.registerExpression("beacon tier of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getState() instanceof org.bukkit.block.Beacon ? ((org.bukkit.block.Beacon) h.getState()).getTier() : null); }); });
        registry.registerExpression("target flower of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getState() instanceof org.bukkit.block.Beehive ? ((org.bukkit.block.Beehive) h.getState()).getFlower() : null); }); });
        registry.registerExpression("%object%'[s] biome", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Location h)) return null; return (h.getBlock().getBiome()); }); });
        registry.registerExpression("block[ ]data of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.block.Block ? ((org.bukkit.block.Block) h).getBlockData() : (h instanceof org.bukkit.entity.BlockDisplay ? ((org.bukkit.entity.BlockDisplay) h).getBlock() : (h instanceof org.bukkit.entity.FallingBlock ? ((org.bukkit.entity.FallingBlock) h).getBlockData() : null))); }); });
        registry.registerExpression("character (from|at|with) code([ ]point| position) %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Integer h)) return null; return (String.valueOf((char) h.intValue())); }); });
        registry.registerExpression("%object%'[s] chunk[s]", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Location h)) return null; return (h.getChunk()); }); });
        registry.registerExpression("[the] [command[ ]block] command of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return ((h instanceof org.bukkit.block.Block && ((org.bukkit.block.Block) h).getState() instanceof org.bukkit.block.CommandBlock) ? (((org.bukkit.block.CommandBlock) ((org.bukkit.block.Block) h).getState()).getCommand().isEmpty() ? null : ((org.bukkit.block.CommandBlock) ((org.bukkit.block.Block) h).getState()).getCommand()) : ((h instanceof org.bukkit.entity.minecart.CommandMinecart) ? (((org.bukkit.entity.minecart.CommandMinecart) h).getCommand().isEmpty() ? null : ((org.bukkit.entity.minecart.CommandMinecart) h).getCommand()) : null)); }); });
        registry.registerExpression("[the] carr(ied|ying) block[[ ]data] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return null; return (h instanceof org.bukkit.entity.Enderman ? ((org.bukkit.entity.Enderman) h).getCarriedBlock() : null); }); });
        registry.registerExpression("[the] entity size of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return null; return (h instanceof org.bukkit.entity.Phantom ? java.lang.Integer.valueOf(((org.bukkit.entity.Phantom) h).getSize()) : (h instanceof org.bukkit.entity.Slime ? java.lang.Integer.valueOf(((org.bukkit.entity.Slime) h).getSize() - 1) : null)); }); });
        registry.registerExpression("[the] [stored] entity count of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getState() instanceof org.bukkit.block.EntityBlockStorage ? java.lang.Integer.valueOf(((org.bukkit.block.EntityBlockStorage<?>) h.getState()).getEntityCount()) : null); }); });
        registry.registerExpression("positive (infinity|∞) [value]", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Double.POSITIVE_INFINITY)));
        registry.registerExpression("[the] (inverse|opposite)[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Boolean h)) return null; return (h == null ? null : !h); }); });
        registry.registerExpression("last damage of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return null; return (h.getLastDamage() / 2); }); });
        registry.registerExpression("last damage (cause|reason|type) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return null; return (h.getLastDamageCause() == null ? org.bukkit.event.entity.EntityDamageEvent.DamageCause.CUSTOM : h.getLastDamageCause().getCause()); }); });
        registry.registerExpression("[(all [[of] the]|the)] [loaded] plugins", Object.class, a -> new ComputedListExpression(ctx -> { java.util.Collection<?> c = (java.util.Arrays.stream(org.bukkit.Bukkit.getPluginManager().getPlugins()).map(org.bukkit.plugin.Plugin::getName).collect(java.util.stream.Collectors.toList())); return c == null ? new Object[0] : c.toArray(); }));
        registry.registerExpression("[the] loot[ ]table[s] %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.String h)) return null; return (org.bukkit.NamespacedKey.fromString(h) != null ? org.bukkit.Bukkit.getLootTable(org.bukkit.NamespacedKey.fromString(h)) : null); }); });
        registry.registerExpression("[the] max[imum] double value", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Double.valueOf(java.lang.Double.MAX_VALUE))));
        registry.registerExpression("[the] max[imum] float value", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Float.valueOf(java.lang.Float.MAX_VALUE))));
        registry.registerExpression("[the] max[imum] integer value", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Integer.valueOf(java.lang.Integer.MAX_VALUE))));
        registry.registerExpression("[the] max[imum] long value", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Long.valueOf(java.lang.Long.MAX_VALUE))));
        registry.registerExpression("[the] max[imum] stack[[ ]size] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.inventory.ItemStack ? java.lang.Integer.valueOf(((org.bukkit.inventory.ItemStack) h).getMaxStackSize()) : (h instanceof org.bukkit.inventory.Inventory ? java.lang.Integer.valueOf(((org.bukkit.inventory.Inventory) h).getMaxStackSize()) : null)); }); });
        registry.registerExpression("[the] (middle|center) [point] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Location h)) return null; return (new org.bukkit.Location(h.getWorld(), h.getBlockX() + 0.5, h.getBlockY(), h.getBlockZ() + 0.5)); }); });
        registry.registerExpression("[the] min[imum] double value", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Double.valueOf(java.lang.Double.MIN_VALUE))));
        registry.registerExpression("[the] min[imum] float value", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Float.valueOf(java.lang.Float.MIN_VALUE))));
        registry.registerExpression("[the] min[imum] integer value", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Integer.valueOf(java.lang.Integer.MIN_VALUE))));
        registry.registerExpression("[the] min[imum] long value", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Long.valueOf(java.lang.Long.MIN_VALUE))));
        registry.registerExpression("NaN [value]", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Double.valueOf(java.lang.Double.NaN))));
        registry.registerExpression("(-|minus |negative )(infinity|∞) [value]", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Double.NEGATIVE_INFINITY)));
        registry.registerExpression("[(all [[of] the]|the)] offline[ ]players", Object.class, a -> new ComputedListExpression(ctx -> { java.util.Collection<?> c = (java.util.Arrays.asList(org.bukkit.Bukkit.getOfflinePlayers())); return c == null ? new Object[0] : c.toArray(); }));
        registry.registerExpression("(current|open|top) inventory of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return (h.getOpenInventory().getTopInventory()); }); });
        registry.registerExpression("(pi|π)", Object.class, a -> new ComputedExpression(ctx -> (Math.PI)));
        registry.registerExpression("(projectile|arrow) critical (state|ability|mode) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Projectile h)) return null; return (h instanceof org.bukkit.entity.AbstractArrow ? Boolean.valueOf(((org.bukkit.entity.AbstractArrow) h).isCritical()) : null); }); });
        registry.registerExpression("[the] resonat(e|ing) time of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getState() instanceof org.bukkit.block.Bell b ? (b.getResonatingTicks() == 0 ? null : b.getResonatingTicks()) : null); }); });
        registry.registerExpression("[the] charge[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getBlockData() instanceof org.bukkit.block.data.type.RespawnAnchor ra ? ra.getCharges() : null); }); });
        registry.registerExpression("[the] ring[ing] time of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getState() instanceof org.bukkit.block.Bell b ? (b.getShakingTicks() == 0 ? null : b.getShakingTicks()) : null); }); });
        registry.registerExpression("[sea] pickle(s| (count|amount)) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getBlockData() instanceof org.bukkit.block.data.type.SeaPickle ? Integer.valueOf(((org.bukkit.block.data.type.SeaPickle) h.getBlockData()).getPickles()) : null); }); });
        registry.registerExpression("[the] shooter of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Projectile h)) return null; return (h.getShooter() instanceof org.bukkit.entity.LivingEntity ? (org.bukkit.entity.LivingEntity) h.getShooter() : null); }); });
        registry.registerExpression("simulation distance[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.World ? Integer.valueOf(((org.bukkit.World) h).getSimulationDistance()) : (h instanceof org.bukkit.entity.Player ? Integer.valueOf(((org.bukkit.entity.Player) h).getSimulationDistance()) : null)); }); });
        registry.registerExpression("(tablist[ed]|listed) players of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return new Object[0]; java.util.Collection<?> c = (org.bukkit.Bukkit.getOnlinePlayers().stream().filter(p -> h.isListed(p)).collect(java.util.stream.Collectors.toList())); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("[the] UUID of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.OfflinePlayer ? ((org.bukkit.OfflinePlayer) h).getUniqueId() : (h instanceof org.bukkit.entity.Entity ? ((org.bukkit.entity.Entity) h).getUniqueId() : (h instanceof org.bukkit.World ? ((org.bukkit.World) h).getUID() : null))); }); });
        registry.registerExpression("[a] random vector", Object.class, a -> new ComputedExpression(ctx -> (new org.bukkit.util.Vector(java.util.concurrent.ThreadLocalRandom.current().nextGaussian(), java.util.concurrent.ThreadLocalRandom.current().nextGaussian(), java.util.concurrent.ThreadLocalRandom.current().nextGaussian()).normalize())));
        registry.registerExpression("[the] view distance[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.entity.Player ? java.lang.Integer.valueOf(((org.bukkit.entity.Player) h).getViewDistance()) : (h instanceof org.bukkit.World ? java.lang.Integer.valueOf(((org.bukkit.World) h).getViewDistance()) : null)); }); });
        registry.registerExpression("villager profession of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return null; return (h instanceof org.bukkit.entity.Villager ? ((org.bukkit.entity.Villager) h).getProfession() : (h instanceof org.bukkit.entity.ZombieVillager ? ((org.bukkit.entity.ZombieVillager) h).getVillagerProfession() : null)); }); });
        registry.registerExpression("villager type of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return null; return (h instanceof org.bukkit.entity.Villager ? ((org.bukkit.entity.Villager) h).getVillagerType() : (h instanceof org.bukkit.entity.ZombieVillager ? ((org.bukkit.entity.ZombieVillager) h).getVillagerType() : null)); }); });
        registry.registerExpression("[the] white[ ]list", Object.class, a -> new ComputedListExpression(ctx -> { java.util.Collection<?> c = (org.bukkit.Bukkit.getServer().getWhitelistedPlayers()); return c == null ? new Object[0] : c.toArray(); }));
        registry.registerExpression("[the] world of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.entity.Entity ? ((org.bukkit.entity.Entity) h).getWorld() : (h instanceof org.bukkit.Location ? ((org.bukkit.Location) h).getWorld() : (h instanceof org.bukkit.Chunk ? ((org.bukkit.Chunk) h).getWorld() : null))); }); });
        registry.registerExpression("world[ ]border of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.World ? ((org.bukkit.World) h).getWorldBorder() : (h instanceof org.bukkit.entity.Player ? ((org.bukkit.entity.Player) h).getWorldBorder() : null)); }); });
        registry.registerExpression("[the] world [(named|with name)] %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.String h)) return null; return (org.bukkit.Bukkit.getWorld(h)); }); });
        registry.registerExpression("[(all [[of] the]|the)] worlds", Object.class, a -> new ComputedListExpression(ctx -> { java.util.Collection<?> c = (org.bukkit.Bukkit.getWorlds()); return c == null ? new Object[0] : c.toArray(); }));
    }
}
