package co.xenastudios.neoskript.lang;

import co.xenastudios.neoskript.api.syntax.Expression;
import co.xenastudios.neoskript.api.registry.SyntaxRegistry;
import co.xenastudios.neoskript.core.expression.ComputedExpression;

/** Generated bulk registration (expr). One registration per line for compile-drop. */
public final class GenExpressions {
    private GenExpressions() {}

    public static void register(SyntaxRegistry registry) {
        registry.registerExpression("active item of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return null; return h.getActiveItem(); }); });
        registry.registerExpression("anvil text input of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.AnvilInventory h)) return null; return h.getRenameText(); }); });
        registry.registerExpression("arrow knockback strength of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.AbstractArrow h)) return null; return h.getKnockbackStrength(); }); });
        registry.registerExpression("arrow pierce level of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Arrow h)) return null; return h.getPierceLevel(); }); });
        registry.registerExpression("bed location of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.OfflinePlayer h)) return null; return h.getBedSpawnLocation(); }); });
        registry.registerExpression("language of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return h.getLocale(); }); });
        registry.registerExpression("last death location of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.OfflinePlayer h)) return null; return h.getLastDeathLocation(); }); });
        registry.registerExpression("resource pack response of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return h.getResourcePackStatus(); }); });
        registry.registerExpression("level of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return h.getLevel(); }); });
        registry.registerExpression("loot location of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.loot.LootContext h)) return null; return h.getLocation(); }); });
        registry.registerExpression("looted entity of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.loot.LootContext h)) return null; return h.getLootedEntity(); }); });
        registry.registerExpression("loot luck value of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.loot.LootContext h)) return null; return h.getLuck(); }); });
        registry.registerExpression("max item use time of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.ItemStack h)) return null; return h.getMaxItemUseDuration(); }); });
        registry.registerExpression("max minecart speed of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Minecart h)) return null; return h.getMaxSpeed(); }); });
        registry.registerExpression("max freeze time of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Entity h)) return null; return h.getMaxFreezeTicks(); }); });
        registry.registerExpression("moon phase of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.World h)) return null; return h.getMoonPhase(); }); });
        registry.registerExpression("no damage time of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return null; return h.getNoDamageTicks(); }); });
        registry.registerExpression("pickup delay of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Item h)) return null; return h.getPickupDelay(); }); });
        registry.registerExpression("player list name of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return h.playerListName(); }); });
        registry.registerExpression("protocol version of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return h.getProtocolVersion(); }); });
        registry.registerExpression("portal cooldown of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Entity h)) return null; return h.getPortalCooldown(); }); });
        registry.registerExpression("potion effect type category of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.potion.PotionEffectType h)) return null; return h.getCategory(); }); });
        registry.registerExpression("redstone power of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return h.getBlockPower(); }); });
        registry.registerExpression("sea level of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.World h)) return null; return h.getSeaLevel(); }); });
        registry.registerExpression("spawn of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.World h)) return null; return h.getSpawnLocation(); }); });
        registry.registerExpression("spectator target of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return h.getSpectatorTarget(); }); });
        registry.registerExpression("namespaced key of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Tag h)) return null; return h.getKey().toString(); }); });
        registry.registerExpression("temperature of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return h.getTemperature(); }); });
        registry.registerExpression("text alignment of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.TextDisplay h)) return null; return h.getAlignment(); }); });
        registry.registerExpression("line width of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.TextDisplay h)) return null; return h.getLineWidth(); }); });
        registry.registerExpression("text of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.TextDisplay h)) return null; return h.text(); }); });
        registry.registerExpression("vector length of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.util.Vector h)) return null; return h.length(); }); });
        registry.registerExpression("squared length of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.util.Vector h)) return null; return h.lengthSquared(); }); });
        registry.registerExpression("client view distance of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return h.getClientViewDistance(); }); });
        registry.registerExpression("world border warning distance of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.WorldBorder h)) return null; return h.getWarningDistance(); }); });
        registry.registerExpression("world border center of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.WorldBorder h)) return null; return h.getCenter(); }); });
        registry.registerExpression("environment of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.World h)) return null; return h.getEnvironment(); }); });
        registry.registerExpression("world border damage amount of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.WorldBorder h)) return null; return h.getDamageAmount(); }); });
        registry.registerExpression("world border damage buffer of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.WorldBorder h)) return null; return h.getDamageBuffer(); }); });
        registry.registerExpression("causing entity of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.damage.DamageSource h)) return null; return h.getCausingEntity(); }); });
        registry.registerExpression("damage location of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.damage.DamageSource h)) return null; return h.getDamageLocation(); }); });
        registry.registerExpression("damage type of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.damage.DamageSource h)) return null; return h.getDamageType(); }); });
        registry.registerExpression("direct entity of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.damage.DamageSource h)) return null; return h.getDirectEntity(); }); });
        registry.registerExpression("food exhaustion of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.damage.DamageSource h)) return null; return h.getFoodExhaustion(); }); });
        registry.registerExpression("source location of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.damage.DamageSource h)) return null; return h.getSourceLocation(); }); });
        registry.registerExpression("difficulty of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.World h)) return null; return h.getDifficulty(); }); });
        registry.registerExpression("billboard of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return h.getBillboard(); }); });
        registry.registerExpression("teleport duration of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return h.getTeleportDuration(); }); });
        registry.registerExpression("view range of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return h.getViewRange(); }); });
        registry.registerExpression("uuid of dropped item owner of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Item h)) return null; return h.getOwner(); }); });
        registry.registerExpression("uuid of dropped item thrower of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Item h)) return null; return h.getThrower(); }); });
        registry.registerExpression("enchantment cost of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.enchantments.EnchantmentOffer h)) return null; return h.getCost(); }); });
        registry.registerExpression("ender chest of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return h.getEnderChest(); }); });
        registry.registerExpression("ai of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return null; return h.hasAI(); }); });
        registry.registerExpression("entity snapshot of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Entity h)) return null; return h.createSnapshot(); }); });
        registry.registerExpression("experience pickup cooldown of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return h.getExpCooldown(); }); });
        registry.registerExpression("flight mode of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return h.getAllowFlight(); }); });
        registry.registerExpression("freeze time of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Entity h)) return null; return h.getFreezeTicks(); }); });
        registry.registerExpression("gliding state of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return null; return h.isGliding(); }); });
        registry.registerExpression("eye location of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return null; return h.getEyeLocation(); }); });
        registry.registerExpression("humidity of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return h.getHumidity(); }); });
        registry.registerExpression("item display transform of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.ItemDisplay h)) return null; return h.getItemDisplayTransform(); }); });
    }
}
