package co.xenastudios.neoskript.lang;

import co.xenastudios.neoskript.api.syntax.Expression;
import co.xenastudios.neoskript.api.registry.SyntaxRegistry;
import co.xenastudios.neoskript.core.expression.ComputedExpression;
import co.xenastudios.neoskript.core.expression.ComputedListExpression;

/** Generated bulk expression registration. One registration per line for compile-drop. */
public final class GenExprBulk2 {
    private GenExprBulk2() {}

    public static void register(SyntaxRegistry registry) {
        registry.registerExpression("alpha (value|component) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Color h)) return null; return (h.getAlpha()); }); });
        registry.registerExpression("red (value|component) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Color h)) return null; return (h.getRed()); }); });
        registry.registerExpression("green (value|component) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Color h)) return null; return (h.getGreen()); }); });
        registry.registerExpression("blue (value|component) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Color h)) return null; return (h.getBlue()); }); });
        registry.registerExpression("%object% [in] deg[ree][s]", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Number h)) return null; return (h); }); });
        registry.registerExpression("%object% [in] rad[ian][s]", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Number h)) return null; return (java.lang.Math.toDegrees(h.doubleValue())); }); });
        registry.registerExpression("[anvil] [item] repair cost of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.Inventory h)) return null; return (h instanceof org.bukkit.inventory.AnvilInventory ? ((org.bukkit.inventory.AnvilInventory) h).getRepairCost() : null); }); });
        registry.registerExpression("[anvil] [item] max[imum] repair cost of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.Inventory h)) return null; return (h instanceof org.bukkit.inventory.AnvilInventory ? ((org.bukkit.inventory.AnvilInventory) h).getMaximumRepairCost() : null); }); });
        registry.registerExpression("[all [[of] the]|the] banner pattern[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.ItemStack h)) return new Object[0]; java.util.Collection<?> c = (h.getItemMeta() instanceof org.bukkit.inventory.meta.BannerMeta bm ? bm.getPatterns() : null); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("[the] honey level of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getBlockData() instanceof org.bukkit.block.data.type.Beehive beehive ? beehive.getHoneyLevel() : null); }); });
        registry.registerExpression("[the] max[imum] honey level of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getBlockData() instanceof org.bukkit.block.data.type.Beehive beehive ? beehive.getMaximumHoneyLevel() : null); }); });
        registry.registerExpression("[book] (author|writer|publisher) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.ItemStack h)) return null; return (h.getItemMeta() instanceof org.bukkit.inventory.meta.BookMeta bm && bm.hasAuthor() ? bm.author() : null); }); });
        registry.registerExpression("[all [[of] the]|the] [book] (pages|content) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.ItemStack h)) return new Object[0]; java.util.Collection<?> c = (h.getType() == org.bukkit.Material.WRITTEN_BOOK && h.getItemMeta() instanceof org.bukkit.inventory.meta.BookMeta bm ? bm.pages() : null); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("book (name|title) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.ItemStack h)) return null; return (h.getItemMeta() instanceof org.bukkit.inventory.meta.BookMeta bm && bm.hasTitle() ? bm.title() : null); }); });
        registry.registerExpression("(dust|brush)[ed|ing] (value|stage|progress[ion]) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getBlockData() instanceof org.bukkit.block.data.Brushable br ? br.getDusted() : null); }); });
        registry.registerExpression("max[imum] (dust|brush)[ed|ing] (value|stage|progress[ion]) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getBlockData() instanceof org.bukkit.block.data.Brushable br ? br.getMaximumDusted() : null); }); });
        registry.registerExpression("a [virtual] world[ ]border", Object.class, a -> new ComputedExpression(ctx -> (org.bukkit.Bukkit.createWorldBorder())));
        registry.registerExpression("[a] custom damage source (with|using) [the|a] [damage type [of]] %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.damage.DamageType h)) return null; return (org.bukkit.damage.DamageSource.builder(h).build()); }); });
        registry.registerExpression("sky (light [level]|brightness) override[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (h.getBrightness() == null ? null : Integer.valueOf(h.getBrightness().getSkyLight())); }); });
        registry.registerExpression("block (light [level]|brightness) override[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (h.getBrightness() == null ? null : Integer.valueOf(h.getBrightness().getBlockLight())); }); });
        registry.registerExpression("(light [level]|brightness) override[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return new Object[0]; java.util.Collection<?> c = (h.getBrightness() == null ? java.util.Collections.emptyList() : java.util.Arrays.asList(Integer.valueOf(h.getBrightness().getBlockLight()), Integer.valueOf(h.getBrightness().getSkyLight()))); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("display height of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (Float.valueOf(h.getDisplayHeight())); }); });
        registry.registerExpression("display width of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (Float.valueOf(h.getDisplayWidth())); }); });
    }
}
