package co.xenastudios.neoskript.lang;

import co.xenastudios.neoskript.api.syntax.Expression;
import co.xenastudios.neoskript.api.registry.SyntaxRegistry;
import co.xenastudios.neoskript.core.expression.ComputedExpression;
import co.xenastudios.neoskript.core.expression.ComputedListExpression;

/** Generated bulk expression registration. One registration per line for compile-drop. */
public final class GenExprBulk2 {
    private GenExprBulk2() {}

    public static void register(SyntaxRegistry registry) {
        registry.registerExpression("[all [[of] the]|the] banned players", Object.class, a -> new ComputedListExpression(ctx -> { java.util.Collection<?> c = (org.bukkit.Bukkit.getBannedPlayers()); return c == null ? new Object[0] : c.toArray(); }));
        registry.registerExpression("[all [[of] the]|the] banned (ips|ip addresses)", Object.class, a -> new ComputedListExpression(ctx -> { java.util.Collection<?> c = (org.bukkit.Bukkit.getIPBans()); return c == null ? new Object[0] : c.toArray(); }));
        registry.registerExpression("[all [[of] the]|the] [server] op[erator]s", Object.class, a -> new ComputedListExpression(ctx -> { java.util.Collection<?> c = (org.bukkit.Bukkit.getOperators()); return c == null ? new Object[0] : c.toArray(); }));
        registry.registerExpression("[all [[of] the]|the] [server] non(-| )op[erator]s", Object.class, a -> new ComputedListExpression(ctx -> { java.util.Collection<?> c = (org.bukkit.Bukkit.getOnlinePlayers().stream().filter(p -> !p.isOp()).collect(java.util.stream.Collectors.toList())); return c == null ? new Object[0] : c.toArray(); }));
        registry.registerExpression("[all [[of] the]] [persistent] data [tag] keys of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.persistence.PersistentDataHolder h)) return new Object[0]; java.util.Collection<?> c = (h.getPersistentDataContainer().getKeys().stream().map(org.bukkit.NamespacedKey::toString).collect(java.util.stream.Collectors.toList())); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("[the] alpha (value|component) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Color h)) return null; return (h.getAlpha()); }); });
        registry.registerExpression("[the] red (value|component) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Color h)) return null; return (h.getRed()); }); });
        registry.registerExpression("[the] green (value|component) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Color h)) return null; return (h.getGreen()); }); });
        registry.registerExpression("[the] blue (value|component) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Color h)) return null; return (h.getBlue()); }); });
        registry.registerExpression("%object% [in] deg[ree][s]", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Number h)) return null; return (h); }); });
        registry.registerExpression("%object% [in] rad[ian][s]", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Number h)) return null; return (java.lang.Math.toDegrees(h.doubleValue())); }); });


        registry.registerExpression("[all [[of] the]|the] banner pattern[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.ItemStack h)) return new Object[0]; java.util.Collection<?> c = (h.getItemMeta() instanceof org.bukkit.inventory.meta.BannerMeta bm ? bm.getPatterns() : null); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("honey level of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getBlockData() instanceof org.bukkit.block.data.type.Beehive bh ? bh.getHoneyLevel() : null); }); });
        registry.registerExpression("max[imum] honey level of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getBlockData() instanceof org.bukkit.block.data.type.Beehive bh ? bh.getMaximumHoneyLevel() : null); }); });
        registry.registerExpression("[book] (author|writer|publisher) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.ItemStack h)) return null; return (h.getItemMeta() instanceof org.bukkit.inventory.meta.BookMeta bm && bm.hasAuthor() ? bm.author() : null); }); });
        registry.registerExpression("[all [[of] the]|the] [book] (pages|content) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.ItemStack h)) return new Object[0]; java.util.Collection<?> c = (h.getType() == org.bukkit.Material.WRITTEN_BOOK && h.getItemMeta() instanceof org.bukkit.inventory.meta.BookMeta bm ? bm.pages() : null); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("book (name|title) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.ItemStack h)) return null; return (h.getItemMeta() instanceof org.bukkit.inventory.meta.BookMeta bm && bm.hasTitle() ? bm.title() : null); }); });
        registry.registerExpression("(dust|brush)[ed|ing] (value|stage|progress[ion]) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getBlockData() instanceof org.bukkit.block.data.Brushable br ? Integer.valueOf(br.getDusted()) : null); }); });
        registry.registerExpression("max[imum] (dust|brush)[ed|ing] (value|stage|progress[ion]) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getBlockData() instanceof org.bukkit.block.data.Brushable br ? Integer.valueOf(br.getMaximumDusted()) : null); }); });
        registry.registerExpression("a [virtual] world[ ]border", Object.class, a -> new ComputedExpression(ctx -> (org.bukkit.Bukkit.createWorldBorder())));
        registry.registerExpression("[a] custom damage source (with|using) [the|a] [damage type [of]] %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.damage.DamageType h)) return null; return (org.bukkit.damage.DamageSource.builder(h).build()); }); });
        registry.registerExpression("sky (light [level]|brightness) override[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (h.getBrightness() == null ? null : Integer.valueOf(h.getBrightness().getSkyLight())); }); });
        registry.registerExpression("block (light [level]|brightness) override[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (h.getBrightness() == null ? null : Integer.valueOf(h.getBrightness().getBlockLight())); }); });
        registry.registerExpression("(light [level]|brightness) override[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return new Object[0]; java.util.Collection<?> c = (h.getBrightness() == null ? null : java.util.Arrays.asList(h.getBrightness().getBlockLight(), h.getBrightness().getSkyLight())); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("display height of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (h.getDisplayHeight()); }); });
        registry.registerExpression("display width of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (h.getDisplayWidth()); }); });
        registry.registerExpression("shadow radius of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (((org.bukkit.entity.Display) h).getShadowRadius()); }); });
        registry.registerExpression("shadow strength of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (((org.bukkit.entity.Display) h).getShadowStrength()); }); });
        registry.registerExpression("left [transformation] rotation of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (((org.bukkit.entity.Display) h).getTransformation().getLeftRotation()); }); });
        registry.registerExpression("right [transformation] rotation of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (((org.bukkit.entity.Display) h).getTransformation().getRightRotation()); }); });
        registry.registerExpression("(display|[display] transformation) scale of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (org.bukkit.util.Vector.fromJOML(((org.bukkit.entity.Display) h).getTransformation().getScale())); }); });
        registry.registerExpression("(display|[display] transformation) translation of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Display h)) return null; return (org.bukkit.util.Vector.fromJOML(((org.bukkit.entity.Display) h).getTransformation().getTranslation())); }); });
        registry.registerExpression("[(all|the|all [of] the)] drops of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return new Object[0]; java.util.Collection<?> c = (((org.bukkit.block.Block) h).getDrops()); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("offline player[s] from %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.util.UUID h)) return null; return (org.bukkit.Bukkit.getOfflinePlayer(h)); }); });
        registry.registerExpression("player[s] from %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.util.UUID h)) return null; return (org.bukkit.Bukkit.getPlayer(h)); }); });
        registry.registerExpression("world[s] from %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.util.UUID h)) return null; return (org.bukkit.Bukkit.getWorld(h)); }); });
        registry.registerExpression("entit(y|ies) from %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.util.UUID h)) return null; return (org.bukkit.Bukkit.getEntity(h)); }); });
        registry.registerExpression("equippable component[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.ItemStack h)) return null; return (h.getData(io.papermc.paper.datacomponent.DataComponentTypes.EQUIPPABLE)); }); });
        registry.registerExpression("camera overlay of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof io.papermc.paper.datacomponent.item.Equippable h)) return null; return (h.cameraOverlay() == null ? null : h.cameraOverlay().toString()); }); });
        registry.registerExpression("equip sound of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof io.papermc.paper.datacomponent.item.Equippable h)) return null; return (h.equipSound() == null ? null : h.equipSound().toString()); }); });
        registry.registerExpression("[the] [server] free (memory|ram)", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Runtime.getRuntime().freeMemory() * 1E-6)));
        registry.registerExpression("[the] [server] max[imum] (memory|ram)", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Runtime.getRuntime().maxMemory() * 1E-6)));
        registry.registerExpression("[the] [server] total (memory|ram)", Object.class, a -> new ComputedExpression(ctx -> (java.lang.Runtime.getRuntime().totalMemory() * 1E-6)));
        registry.registerExpression("interaction height[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Interaction h)) return null; return (h.getInteractionHeight()); }); });
        registry.registerExpression("interaction width[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Interaction h)) return null; return (h.getInteractionWidth()); }); });
        registry.registerExpression("holder[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.Inventory h)) return null; return (h.getHolder()); }); });
        registry.registerExpression("viewers of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.Inventory h)) return new Object[0]; java.util.Collection<?> c = (h.getViewers().stream().filter(v -> v instanceof org.bukkit.entity.Player).collect(java.util.stream.Collectors.toList())); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("[amount of] rows of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.Inventory h)) return null; return (h.getSize() < 9 ? 1 : h.getSize() / 9); }); });
        registry.registerExpression("[amount of] slots of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.Inventory h)) return null; return (h.getSize()); }); });
        registry.registerExpression("[the] last player[s] to attack %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Interaction h)) return null; return (h.getLastAttack() != null ? h.getLastAttack().getPlayer() : null); }); });
        registry.registerExpression("[the] last player[s] (who|that) attacked %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Interaction h)) return null; return (h.getLastAttack() != null ? h.getLastAttack().getPlayer() : null); }); });
        registry.registerExpression("[the] last player[s] to interact with %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Interaction h)) return null; return (h.getLastInteraction() != null ? h.getLastInteraction().getPlayer() : null); }); });
        registry.registerExpression("[the] last player[s] (who|that) interacted with %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Interaction h)) return null; return (h.getLastInteraction() != null ? h.getLastInteraction().getPlayer() : null); }); });
        registry.registerExpression("light level of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Location h)) return null; return (((org.bukkit.Location) h).getBlock().getLightLevel()); }); });
        registry.registerExpression("sky light level of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Location h)) return null; return (((org.bukkit.Location) h).getBlock().getLightFromSky()); }); });
        registry.registerExpression("block light level of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Location h)) return null; return (((org.bukkit.Location) h).getBlock().getLightFromBlocks()); }); });
        registry.registerExpression("(location|position) of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Location h)) return null; return (h); }); });
        registry.registerExpression("[the] highest [solid] block (at|of) %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.Location h)) return null; return (h.getWorld() == null ? null : h.getWorld().getHighestBlockAt(h)); }); });
        registry.registerExpression("[the] default (MOTD|message of [the] day)", Object.class, a -> new ComputedExpression(ctx -> (org.bukkit.Bukkit.motd())));
        registry.registerExpression("[the] [minecart] derailed velocity of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Minecart h)) return null; return (h.getDerailedVelocityMod()); }); });
        registry.registerExpression("[the] [minecart] flying velocity of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Minecart h)) return null; return (h.getFlyingVelocityMod()); }); });
        registry.registerExpression("number of upper[ ]case char(acters|s) in %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.String h)) return null; return (h.codePoints().filter(java.lang.Character::isUpperCase).count()); }); });
        registry.registerExpression("number of lower[ ]case char(acters|s) in %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.String h)) return null; return (h.codePoints().filter(java.lang.Character::isLowerCase).count()); }); });
        registry.registerExpression("number of digit char(acters|s) in %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.String h)) return null; return (h.codePoints().filter(java.lang.Character::isDigit).count()); }); });
        registry.registerExpression("main gene[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Panda h)) return null; return (h.getMainGene()); }); });
        registry.registerExpression("hidden gene[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Panda h)) return null; return (h.getHiddenGene()); }); });
        registry.registerExpression("(player|tab)[ ]list header [text|message] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return (h.playerListHeader()); }); });
        registry.registerExpression("(player|tab)[ ]list footer [text|message] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return (h.playerListFooter()); }); });
        registry.registerExpression("([potion] amplifier|potion tier|potion level)[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.potion.PotionEffect h)) return null; return (h.getAmplifier() + 1); }); });
        registry.registerExpression("active potion effects of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return new Object[0]; java.util.Collection<?> c = (h.getActivePotionEffects()); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("potion effects of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.LivingEntity h)) return new Object[0]; java.util.Collection<?> c = (h.getActivePotionEffects()); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("raw %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.String h)) return null; return (h == null ? null : net.kyori.adventure.text.Component.text(h)); }); });
        registry.registerExpression("rotation axis of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.joml.Quaternionf h)) return null; return (new org.bukkit.util.Vector(new org.joml.AxisAngle4f().set(h).x, new org.joml.AxisAngle4f().set(h).y, new org.joml.AxisAngle4f().set(h).z)); }); });
        registry.registerExpression("rotation angle of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.joml.Quaternionf h)) return null; return ((float) (new org.joml.AxisAngle4f().set(h).angle * 180 / java.lang.Math.PI)); }); });



        registry.registerExpression("loot[[ ]table] seed[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.block.Block b ? (b.getState() instanceof org.bukkit.loot.Lootable l ? l.getSeed() : null) : (h instanceof org.bukkit.loot.Lootable l2 ? l2.getSeed() : null)); }); });
        registry.registerExpression("(head|skull) owner of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.block.Block b && b.getState() instanceof org.bukkit.block.Skull sk ? (sk.getPlayerProfile() == null ? null : (sk.getPlayerProfile().getId() != null ? org.bukkit.Bukkit.getOfflinePlayer(sk.getPlayerProfile().getId()) : (sk.getPlayerProfile().getName() != null ? org.bukkit.Bukkit.getOfflinePlayer(sk.getPlayerProfile().getName()) : null))) : (h instanceof org.bukkit.inventory.ItemStack it && it.getItemMeta() instanceof org.bukkit.inventory.meta.SkullMeta sm ? (sm.getPlayerProfile() == null ? null : (sm.getPlayerProfile().getId() != null ? org.bukkit.Bukkit.getOfflinePlayer(sm.getPlayerProfile().getId()) : (sm.getPlayerProfile().getName() != null ? org.bukkit.Bukkit.getOfflinePlayer(sm.getPlayerProfile().getName()) : null))) : null)); }); });
        registry.registerExpression("spawn egg entity of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.inventory.ItemStack h)) return null; return (h.getItemMeta() instanceof org.bukkit.inventory.meta.SpawnEggMeta m ? m.getSpawnedEntity() : null); }); });
        registry.registerExpression("(spawner|entity|creature) type[s] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.block.Block h)) return null; return (h.getState() instanceof org.bukkit.block.CreatureSpawner cs ? cs.getSpawnedType() : (h.getState() instanceof org.bukkit.block.TrialSpawner ts ? (ts.isOminous() ? ts.getOminousConfiguration().getSpawnedType() : ts.getNormalConfiguration().getSpawnedType()) : null)); }); });
        registry.registerExpression("walk[ing][( |-)]speed of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return (h.getWalkSpeed()); }); });
        registry.registerExpression("fl(y[ing]|ight)[( |-)]speed of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Player h)) return null; return (h.getFlySpeed()); }); });
        registry.registerExpression("test string literal %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.String h)) return null; return (h); }); });
        registry.registerExpression("tps from [the] last 1 minute", Object.class, a -> new ComputedExpression(ctx -> (org.bukkit.Bukkit.getServer().getTPS()[0])));
        registry.registerExpression("tps from [the] last 5 minutes", Object.class, a -> new ComputedExpression(ctx -> (org.bukkit.Bukkit.getServer().getTPS()[1])));
        registry.registerExpression("tps from [the] last 15 minutes", Object.class, a -> new ComputedExpression(ctx -> (org.bukkit.Bukkit.getServer().getTPS()[2])));
        registry.registerExpression("[the] tps", Object.class, a -> new ComputedListExpression(ctx -> { java.util.Collection<?> c = (java.util.Arrays.stream(org.bukkit.Bukkit.getServer().getTPS()).boxed().collect(java.util.stream.Collectors.toList())); return c == null ? new Object[0] : c.toArray(); }));
        registry.registerExpression("[the] [vector|quaternion] x [component[s]] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.util.Vector ? (java.lang.Number) java.lang.Double.valueOf(((org.bukkit.util.Vector) h).getX()) : (h instanceof org.joml.Quaternionf ? (java.lang.Number) java.lang.Float.valueOf(((org.joml.Quaternionf) h).x()) : null)); }); });
        registry.registerExpression("[the] [vector|quaternion] y [component[s]] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.util.Vector ? (java.lang.Number) java.lang.Double.valueOf(((org.bukkit.util.Vector) h).getY()) : (h instanceof org.joml.Quaternionf ? (java.lang.Number) java.lang.Float.valueOf(((org.joml.Quaternionf) h).y()) : null)); }); });
        registry.registerExpression("[the] [vector|quaternion] z [component[s]] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.util.Vector ? (java.lang.Number) java.lang.Double.valueOf(((org.bukkit.util.Vector) h).getZ()) : (h instanceof org.joml.Quaternionf ? (java.lang.Number) java.lang.Float.valueOf(((org.joml.Quaternionf) h).z()) : null)); }); });
        registry.registerExpression("[the] [vector|quaternion] w [component[s]] of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.joml.Quaternionf ? (java.lang.Number) java.lang.Float.valueOf(((org.joml.Quaternionf) h).w()) : null); }); });
        registry.registerExpression("[craft]bukkit( |-)version", Object.class, a -> new ComputedExpression(ctx -> ("" + org.bukkit.Bukkit.getBukkitVersion())));
        registry.registerExpression("villager level of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Villager h)) return null; return (h.getVillagerLevel()); }); });
        registry.registerExpression("villager experience of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof org.bukkit.entity.Villager h)) return null; return (h.getVillagerExperience()); }); });
        registry.registerExpression("%object% time[s]", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedListExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Number h)) return new Object[0]; java.util.Collection<?> c = (java.util.stream.LongStream.rangeClosed(1L, (long)(((java.lang.Number)h).doubleValue() + 1e-10)).boxed().collect(java.util.stream.Collectors.toList())); return c == null ? new Object[0] : c.toArray(); }); });
        registry.registerExpression("once", Object.class, a -> new ComputedListExpression(ctx -> { java.util.Collection<?> c = (java.util.Arrays.asList(1L)); return c == null ? new Object[0] : c.toArray(); }));
        registry.registerExpression("twice", Object.class, a -> new ComputedListExpression(ctx -> { java.util.Collection<?> c = (java.util.Arrays.asList(1L, 2L)); return c == null ? new Object[0] : c.toArray(); }));
        registry.registerExpression("thrice", Object.class, a -> new ComputedListExpression(ctx -> { java.util.Collection<?> c = (java.util.Arrays.asList(1L, 2L, 3L)); return c == null ? new Object[0] : c.toArray(); }));
        registry.registerExpression("yaw of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.entity.Entity ? (org.bukkit.Location.normalizeYaw(((org.bukkit.entity.Entity)h).getLocation().getYaw()) < 0f ? org.bukkit.Location.normalizeYaw(((org.bukkit.entity.Entity)h).getLocation().getYaw()) + 360f : org.bukkit.Location.normalizeYaw(((org.bukkit.entity.Entity)h).getLocation().getYaw())) : (h instanceof org.bukkit.Location ? (org.bukkit.Location.normalizeYaw(((org.bukkit.Location)h).getYaw()) < 0f ? org.bukkit.Location.normalizeYaw(((org.bukkit.Location)h).getYaw()) + 360f : org.bukkit.Location.normalizeYaw(((org.bukkit.Location)h).getYaw())) : (h instanceof org.bukkit.util.Vector ? ((((org.bukkit.util.Vector)h).getX()==0.0 && ((org.bukkit.util.Vector)h).getZ()==0.0 ? 0f : (float)(java.lang.Math.atan2(((org.bukkit.util.Vector)h).getZ(), ((org.bukkit.util.Vector)h).getX()) * (180.0/java.lang.Math.PI))) < 90f ? (((org.bukkit.util.Vector)h).getX()==0.0 && ((org.bukkit.util.Vector)h).getZ()==0.0 ? 0f : (float)(java.lang.Math.atan2(((org.bukkit.util.Vector)h).getZ(), ((org.bukkit.util.Vector)h).getX()) * (180.0/java.lang.Math.PI))) + 270f : (((org.bukkit.util.Vector)h).getX()==0.0 && ((org.bukkit.util.Vector)h).getZ()==0.0 ? 0f : (float)(java.lang.Math.atan2(((org.bukkit.util.Vector)h).getZ(), ((org.bukkit.util.Vector)h).getX()) * (180.0/java.lang.Math.PI))) - 90f) : null))); }); });
        registry.registerExpression("pitch of %object%", Object.class, a -> { Expression<?> src = a.get(0); return new ComputedExpression(ctx -> { Object o = src.getSingle(ctx); if (!(o instanceof java.lang.Object h)) return null; return (h instanceof org.bukkit.entity.Entity ? ((org.bukkit.entity.Entity)h).getLocation().getPitch() : (h instanceof org.bukkit.Location ? ((org.bukkit.Location)h).getPitch() : (h instanceof org.bukkit.util.Vector ? -(float)(java.lang.Math.atan(((org.bukkit.util.Vector)h).getY() / java.lang.Math.sqrt(((org.bukkit.util.Vector)h).getX()*((org.bukkit.util.Vector)h).getX() + ((org.bukkit.util.Vector)h).getZ()*((org.bukkit.util.Vector)h).getZ())) * (180.0/java.lang.Math.PI)) : null))); }); });
    }
}
