package co.xenastudios.neoskript.lang;

import co.xenastudios.neoskript.api.registry.SyntaxRegistry;
import co.xenastudios.neoskript.core.expression.ComputedExpression;
import co.xenastudios.neoskript.core.expression.ComputedListExpression;

/** Generated event-value expressions (source-grounded). One per line for compile-drop. */
public final class GenEventValues {
    private GenEventValues() {}

    public static void register(SyntaxRegistry registry) {
        registry.registerExpression("[the] absorbed blocks", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = (ev instanceof org.bukkit.event.block.SpongeAbsorbEvent _e ? _e.getBlocks() : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] affected entities", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = (ev instanceof org.bukkit.event.entity.AreaEffectCloudApplyEvent _e ? _e.getAffectedEntities() : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] applied [beacon] effect", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof com.destroystokyo.paper.event.block.BeaconEffectEvent _e ? _e.getEffect().getType() : null); }));
        registry.registerExpression("[the] (attacked|damaged|victim)", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.entity.ProjectileHitEvent _ph ? _ph.getHitEntity() : (ev instanceof org.bukkit.event.entity.EntityEvent _ee ? _ee.getEntity() : (ev instanceof org.bukkit.event.vehicle.VehicleEvent _ve ? _ve.getVehicle() : (ev instanceof io.papermc.paper.event.player.PrePlayerAttackEntityEvent _pa ? _pa.getAttacked() : null)))); }));
        registry.registerExpression("[the] (attacker|damager)", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.entity.EntityDamageByEntityEvent _e ? (_e.getDamager() instanceof org.bukkit.entity.Projectile _p ? (_p.getShooter() instanceof org.bukkit.entity.Entity _s ? _s : null) : _e.getDamager()) : (ev instanceof org.bukkit.event.entity.EntityDeathEvent _d ? (_d.getEntity().getLastDamageCause() instanceof org.bukkit.event.entity.EntityDamageByEntityEvent _c ? (_c.getDamager() instanceof org.bukkit.entity.Projectile _p2 ? (_p2.getShooter() instanceof org.bukkit.entity.Entity _s2 ? _s2 : null) : _c.getDamager()) : null) : (ev instanceof org.bukkit.event.vehicle.VehicleDamageEvent _vd ? _vd.getAttacker() : (ev instanceof org.bukkit.event.vehicle.VehicleDestroyEvent _vx ? _vx.getAttacker() : (ev instanceof io.papermc.paper.event.player.PrePlayerAttackEntityEvent _pa ? _pa.getPlayer() : null))))); }));
        registry.registerExpression("[the] [piglin] barter[ing] drops", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = (ev instanceof org.bukkit.event.entity.PiglinBarterEvent _e ? _e.getOutcome() : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] [piglin] barter[ing] input", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.entity.PiglinBarterEvent _e ? _e.getInput() : null); }));
        registry.registerExpression("[the] brewing results", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = (ev instanceof org.bukkit.event.inventory.BrewEvent _e ? _e.getResults() : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] broadcast(-|[ed] )message", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.server.BroadcastMessageEvent _e ? _e.message() : null); }));
        registry.registerExpression("[the] [chat( |-)]message", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof io.papermc.paper.event.player.AsyncChatEvent _e ? _e.message() : null); }));
        registry.registerExpression("[the] [chat( | -)]recipients", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = (ev instanceof io.papermc.paper.event.player.AsyncChatEvent _e ? _e.viewers() : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] (full|complete|whole) command", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerCommandPreprocessEvent _p ? _p.getMessage().substring(1).trim() : (ev instanceof org.bukkit.event.server.ServerCommandEvent _s ? _s.getCommand().trim() : null)); }));
        registry.registerExpression("[the] consumed item", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.entity.EntityShootBowEvent _b ? _b.getConsumable() : (ev instanceof org.bukkit.event.player.PlayerItemConsumeEvent _c ? _c.getItem() : null)); }));
        registry.registerExpression("[the] damage", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.vehicle.VehicleDamageEvent _v ? _v.getDamage() : (ev instanceof org.bukkit.event.player.PlayerItemDamageEvent _i ? _i.getDamage() : (ev instanceof org.bukkit.event.entity.EntityDamageEvent _e ? _e.getDamage() / 2.0 : null))); }));
        registry.registerExpression("[the] drops", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = (ev instanceof org.bukkit.event.entity.EntityDeathEvent _d ? _d.getDrops() : (ev instanceof org.bukkit.event.player.PlayerHarvestBlockEvent _h ? _h.getItemsHarvested() : null)); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] enchant[ed] item", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.enchantment.PrepareItemEnchantEvent _p ? _p.getItem() : (ev instanceof org.bukkit.event.enchantment.EnchantItemEvent _e ? _e.getItem() : null)); }));
        registry.registerExpression("[the] [displayed] ([e]xp[erience]|enchanting) cost", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.enchantment.EnchantItemEvent _e ? (long) _e.getExpLevelCost() : null); }));
        registry.registerExpression("[the] enchantment bonus", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.enchantment.PrepareItemEnchantEvent _e ? (long) _e.getEnchantmentBonus() : null); }));
        registry.registerExpression("[the] exploded blocks", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = (ev instanceof org.bukkit.event.entity.EntityExplodeEvent _e ? _e.blockList() : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] [explosion['s]] block (yield|amount)", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.entity.EntityExplodeEvent _e ? _e.getYield() : null); }));
        registry.registerExpression("[the] explosion (yield|radius|size)", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.entity.ExplosionPrimeEvent _e ? _e.getRadius() : null); }));
        registry.registerExpression("fish[ing] bit(e|ing) [wait] time", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerFishEvent _e ? (Object) java.lang.Integer.valueOf(_e.getHook().getTimeUntilBite()) : null); }));
        registry.registerExpression("fish[ing] (hook|bobber)", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerFishEvent _e ? _e.getHook() : null); }));
        registry.registerExpression("[the] hook[ed] entity", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerFishEvent _e ? _e.getHook().getHookedEntity() : null); }));
        registry.registerExpression("[the] (smelted item|result[ item]|extracted item[s]|smelting item|burned (fuel|item))", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.inventory.FurnaceSmeltEvent _s ? _s.getResult() : (ev instanceof org.bukkit.event.inventory.FurnaceStartSmeltEvent _t ? _t.getSource() : (ev instanceof org.bukkit.event.inventory.FurnaceBurnEvent _b ? _b.getFuel() : (ev instanceof org.bukkit.event.inventory.FurnaceExtractEvent _x ? new org.bukkit.inventory.ItemStack(_x.getItemType(), _x.getItemAmount()) : null)))); }));
        registry.registerExpression("[the] hatching entity [type]", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerEggThrowEvent _e ? _e.getHatchingType() : null); }));
        registry.registerExpression("[the] hatching number", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerEggThrowEvent _e ? _e.getNumHatches() : null); }));
        registry.registerExpression("[the] heal[ing] amount", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.entity.EntityRegainHealthEvent _e ? _e.getAmount() : null); }));
        registry.registerExpression("(regen|health regain|heal[ing]) (reason|cause)", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.entity.EntityRegainHealthEvent _e ? _e.getRegainReason() : null); }));
        registry.registerExpression("[the] (host|domain)[ ][name]", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerLoginEvent _e ? _e.getHostname() : null); }));
        registry.registerExpression("[the] hotbar button", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.inventory.InventoryClickEvent _e ? (long) _e.getHotbarButton() : null); }));
        registry.registerExpression("[the] [custom] [player|server] (hover|sample) ([message] list|message)", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = (ev instanceof com.destroystokyo.paper.event.server.PaperServerListPingEvent _e ? _e.getListedPlayers().stream().map(com.destroystokyo.paper.event.server.PaperServerListPingEvent.ListedPlayerInfo::name).toArray(String[]::new) : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] [event-]initiator[( |-)inventory]", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.inventory.InventoryMoveItemEvent _e ? _e.getInitiator() : null); }));
        registry.registerExpression("inventory action", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.inventory.InventoryClickEvent _e ? _e.getAction() : null); }));
        registry.registerExpression("[the] inventory clos(e|ing) (reason|cause)", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.inventory.InventoryCloseEvent _e ? _e.getReason() : null); }));
        registry.registerExpression("[the] (join|log[ ]in)( |-)message", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerJoinEvent _e ? _e.joinMessage() : null); }));
        registry.registerExpression("[the] kick( |-)message", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerKickEvent _e ? _e.leaveMessage() : null); }));
        registry.registerExpression("[the] loot", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = (ev instanceof org.bukkit.event.world.LootGenerateEvent _e ? _e.getLoot() : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] [mending] repair amount", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerItemMendEvent _e ? (long) _e.getRepairAmount() : null); }));
        registry.registerExpression("[the] moved blocks", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = (ev instanceof org.bukkit.event.block.BlockPistonExtendEvent _e ? _e.getBlocks() : (ev instanceof org.bukkit.event.block.BlockPistonRetractEvent _r ? _r.getBlocks() : null)); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] on-screen kick message", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerKickEvent _e ? _e.reason() : null); }));
        registry.registerExpression("[the] portal['s] blocks", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = (ev instanceof org.bukkit.event.world.PortalCreateEvent _e ? _e.getBlocks().stream().map(org.bukkit.block.BlockState::getBlock).collect(java.util.stream.Collectors.toList()) : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] projectile force", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.entity.EntityShootBowEvent _e ? _e.getForce() : null); }));
        registry.registerExpression("[the] [server] [(sent|required|fake)] protocol version [number]", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof com.destroystokyo.paper.event.server.PaperServerListPingEvent _e ? (long) _e.getProtocolVersion() : null); }));
        registry.registerExpression("[the] (quit|leave|log[ ]out)( |-)message", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerQuitEvent _e ? _e.quitMessage() : null); }));
        registry.registerExpression("[the] (readied|selected|drawn) arrow", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof com.destroystokyo.paper.event.player.PlayerReadyArrowEvent _e ? _e.getArrow() : null); }));
        registry.registerExpression("[the] (readied|selected|drawn) bow", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof com.destroystokyo.paper.event.player.PlayerReadyArrowEvent _e ? _e.getBow() : null); }));
        registry.registerExpression("[the] respawn location", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerRespawnEvent _e ? _e.getRespawnLocation() : null); }));
        registry.registerExpression("[the] [sent] [server] command[s] list", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = (ev instanceof org.bukkit.event.player.PlayerCommandSendEvent _e ? _e.getCommands() : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] (shown|sent) [server] icon", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof com.destroystokyo.paper.event.server.PaperServerListPingEvent _e && _e.getServerIcon() != null && _e.getServerIcon().getData() != null ? _e.getServerIcon() : null); }));
        registry.registerExpression("[the] source block", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.block.BlockSpreadEvent _e ? _e.getSource() : null); }));
        registry.registerExpression("[the] tamer", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.entity.EntityTameEvent _e && _e.getOwner() instanceof org.bukkit.entity.Player _p ? _p : null); }));
        registry.registerExpression("teleport (cause|reason|type)", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerTeleportEvent _e ? _e.getCause() : null); }));
        registry.registerExpression("[thrown] egg", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.player.PlayerEggThrowEvent _e ? _e.getEgg() : null); }));
        registry.registerExpression("[the] transform[ing] (cause|reason|type)", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.entity.EntityTransformEvent _e ? _e.getTransformReason() : null); }));
        registry.registerExpression("[the] unleash[ing] reason", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof org.bukkit.event.entity.EntityUnleashEvent _e ? _e.getReason() : null); }));
        registry.registerExpression("[the] [shown|custom] version [string|text]", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return null; return (ev instanceof com.destroystokyo.paper.event.server.PaperServerListPingEvent _e ? _e.getVersion() : null); }));
    }
}
