package co.xenastudios.neoskript.lang;

import co.xenastudios.neoskript.api.registry.SyntaxRegistry;
import co.xenastudios.neoskript.core.expression.ComputedExpression;
import co.xenastudios.neoskript.core.expression.ComputedListExpression;

/** Generated event-restricted expressions/conditions/effects (source-grounded). */
public final class GenEventBulk {
    private GenEventBulk() {}

    public static void register(SyntaxRegistry registry) {
        registry.registerCondition("[the] brewing stand will consume [the] fuel", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev != null && (ev instanceof org.bukkit.event.inventory.BrewingStandFuelEvent _e && _e.isConsuming()); });
        registry.registerCondition("[the] egg will hatch", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev != null && (ev instanceof org.bukkit.event.player.PlayerEggThrowEvent _e && _e.isHatching()); });
        registry.registerCondition("[the] event is cancel[l]ed", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev != null && (ev instanceof org.bukkit.event.Cancellable _e && _e.isCancelled()); });
        registry.registerCondition("lure enchantment bonus is (applied|active)", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev != null && (ev instanceof org.bukkit.event.player.PlayerFishEvent _e && _e.getHook().getApplyLure()); });
        registry.registerCondition("[the] respawn location (was|is) [a] bed", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev != null && (ev instanceof org.bukkit.event.player.PlayerRespawnEvent _e && _e.isBedSpawn()); });
        registry.registerCondition("[the] respawn location (was|is) [a] respawn anchor", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev != null && (ev instanceof org.bukkit.event.player.PlayerRespawnEvent _e && _e.isAnchorSpawn()); });
        registry.registerCondition("[the] (lead|leash) [item] will (drop|be dropped)", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev != null && (ev instanceof org.bukkit.event.entity.EntityUnleashEvent _e && _e.isDropLeash()); });
        registry.registerCondition("[the] (boosting|used) firework will be consumed", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev != null && (ev instanceof com.destroystokyo.paper.event.player.PlayerElytraBoostEvent _e && _e.shouldConsume()); });
        registry.registerEffect("(force|allow) [the] (lead|leash) [item] to drop", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev != null) { if (ev instanceof org.bukkit.event.entity.EntityUnleashEvent _e) _e.setDropLeash(true);; } });
        registry.registerEffect("apply [the] lure enchantment bonus", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev != null) { if (ev instanceof org.bukkit.event.player.PlayerFishEvent _e) _e.getHook().setApplyLure(true);; } });
        registry.registerEffect("(cancel|clear|delete) [the] drops", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev != null) { if (ev instanceof org.bukkit.event.entity.EntityDeathEvent _d) { _d.getDrops().clear(); _d.setDroppedExp(0); } else if (ev instanceof org.bukkit.event.block.BlockBreakEvent _b) { _b.setDropItems(false); _b.setExpToDrop(0); } else if (ev instanceof org.bukkit.event.block.BlockDropItemEvent _di) { _di.getItems().forEach(org.bukkit.entity.Item::remove); } else if (ev instanceof org.bukkit.event.player.PlayerHarvestBlockEvent _h) { _h.getItemsHarvested().clear(); }; } });
        registry.registerEffect("(prevent|disallow) [the] (boosting|used) firework from being consumed", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev != null) { if (ev instanceof com.destroystokyo.paper.event.player.PlayerElytraBoostEvent _e) _e.setShouldConsume(false);; } });
        registry.registerEffect("make [the] brewing stand consume [its|the] fuel", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev != null) { if (ev instanceof org.bukkit.event.inventory.BrewingStandFuelEvent _e) _e.setConsuming(true);; } });
        registry.registerEffect("keep [the] (inventory|items)", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev != null) { if (ev instanceof org.bukkit.event.entity.PlayerDeathEvent _e) _e.setKeepInventory(true);; } });
        registry.registerEffect("make [the] egg hatch", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev != null) { if (ev instanceof org.bukkit.event.player.PlayerEggThrowEvent _e) { _e.setHatching(true); if (_e.getNumHatches() == 0) _e.setNumHatches((byte) 1); }; } });
        registry.registerEffect("hide [all] player [related] info[rmation] [(in|on|from) [the] server list]", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev != null) { if (ev instanceof com.destroystokyo.paper.event.server.PaperServerListPingEvent _e) _e.setHidePlayers(true);; } });
        registry.registerEffect("(reel|pull) in [the] hook[ed] entity", a -> ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev != null) { if (ev instanceof org.bukkit.event.player.PlayerFishEvent _e) _e.getHook().pullHookedEntity();; } });
        registry.registerExpression("(old|unequipped) armo[u]r item", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : (ev instanceof com.destroystokyo.paper.event.player.PlayerArmorChangeEvent _e ? _e.getOldItem() : null); }));
        registry.registerExpression("[the] breeding mother", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : (ev instanceof org.bukkit.event.entity.EntityBreedEvent _e ? _e.getMother() : null); }));
        registry.registerExpression("[the] breeding father", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : (ev instanceof org.bukkit.event.entity.EntityBreedEvent _e ? _e.getFather() : null); }));
        registry.registerExpression("[the] [bred] (offspring|child)", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : (ev instanceof org.bukkit.event.entity.EntityBreedEvent _e ? _e.getEntity() : null); }));
        registry.registerExpression("[the] breeder", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : (ev instanceof org.bukkit.event.entity.EntityBreedEvent _e ? _e.getBreeder() : null); }));
        registry.registerExpression("[all [of]] [the] enchant[ment] offers", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = (ev instanceof org.bukkit.event.enchantment.PrepareItemEnchantEvent _e ? _e.getOffers() : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("[the] (spawned|dropped|) [e]xp[erience] [orb[s]]", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : ((ev instanceof org.bukkit.event.block.BlockBreakEvent _bb) ? (Object) Integer.valueOf(_bb.getExpToDrop()) : (ev instanceof org.bukkit.event.player.PlayerExpChangeEvent _ec) ? (Object) Integer.valueOf(_ec.getAmount()) : (ev instanceof org.bukkit.event.entity.EntityBreedEvent _eb) ? (Object) Integer.valueOf(_eb.getExperience()) : (ev instanceof org.bukkit.event.player.PlayerFishEvent _pf) ? (Object) Integer.valueOf(_pf.getExpToDrop()) : null); }));
        registry.registerExpression("(experience|[e]xp) cooldown change (reason|cause|type)", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : ((ev instanceof org.bukkit.event.player.PlayerExpCooldownChangeEvent _e) ? _e.getReason() : null); }));
        registry.registerExpression("[all] [the] fertilized blocks", Object.class, a -> new ComputedListExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); if (ev == null) return new Object[0]; Object _c = ((ev instanceof org.bukkit.event.block.BlockFertilizeEvent _e) ? _e.getBlocks() : null); if (_c == null) return new Object[0]; if (_c instanceof java.util.Collection<?> _col) return _col.toArray(); if (_c instanceof Object[] _arr) return _arr; return new Object[]{_c}; }));
        registry.registerExpression("min[imum] fish[ing] approach[ing] angle", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : ((ev instanceof org.bukkit.event.player.PlayerFishEvent _e) ? Float.valueOf(_e.getHook().getMinLureAngle()) : null); }));
        registry.registerExpression("max[imum] fish[ing] approach[ing] angle", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : ((ev instanceof org.bukkit.event.player.PlayerFishEvent _e) ? Float.valueOf(_e.getHook().getMaxLureAngle()) : null); }));
        registry.registerExpression("[the] hanging entity", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : (ev instanceof org.bukkit.event.hanging.HangingEvent _e ? _e.getEntity() : null); }));
        registry.registerExpression("item", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : (ev instanceof org.bukkit.event.block.BlockDispenseEvent _d ? _d.getItem() : ev instanceof org.bukkit.event.player.PlayerItemConsumeEvent _c ? _c.getItem() : ev instanceof org.bukkit.event.player.PlayerItemBreakEvent _b ? _b.getBrokenItem() : ev instanceof org.bukkit.event.entity.EntityPickupItemEvent _p ? _p.getItem().getItemStack() : ev instanceof org.bukkit.event.player.PlayerDropItemEvent _dr ? _dr.getItemDrop().getItemStack() : null); }));
        registry.registerExpression("[the] [event-](location|position)", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : (ev instanceof org.bukkit.event.entity.EntityEvent _ee && _ee.getEntity() != null ? _ee.getEntity().getLocation() : (ev instanceof org.bukkit.event.block.BlockEvent _be && _be.getBlock() != null ? _be.getBlock().getLocation().add(0.5, 0.5, 0.5) : null)); }));
        registry.registerExpression("loot[ ]context", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : (ev instanceof org.bukkit.event.world.LootGenerateEvent _e ? _e.getLootContext() : null); }));
        registry.registerExpression("[the] picked block", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : (ev instanceof io.papermc.paper.event.player.PlayerPickBlockEvent _e ? _e.getBlock() : null); }));
        registry.registerExpression("[the] picked entity", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : (ev instanceof io.papermc.paper.event.player.PlayerPickEntityEvent _e ? _e.getEntity() : null); }));
        registry.registerExpression("(quit|disconnect) (cause|reason)", Object.class, a -> new ComputedExpression(ctx -> { org.bukkit.event.Event ev = ctx.event().orElse(null); return ev == null ? null : (ev instanceof org.bukkit.event.player.PlayerQuitEvent _e ? _e.getReason() : null); }));
    }
}
